//! Types shared between the Tauri backend (`src-tauri`) and the Leptos
//! frontend (`src`). Keeping them here avoids duplicating serde definitions
//! and ensures both sides agree on a serialization format over the IPC bridge.

use std::collections::BTreeSet;
use std::fmt;

use mathdoku::{Cell, Grid, Polyomino, Puzzle};
use serde::{Deserialize, Serialize};

/// Document state returned by `get_doc_state`.
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct DocState {
    pub dirty: bool,
    pub path: Option<String>,
}

/// Result of `save_puzzle`, carrying the path that was written.
#[derive(Clone, Serialize, Deserialize)]
pub struct SaveResult {
    pub path: String,
}

/// Full designer state: the unit of serialization for save files and undo/redo.
///
/// The `solution` field discriminates the two authoring modes:
///
/// - `Some(grid)` — **With Solution**: a fixed Latin Square was generated at
///   creation and cage targets are read off it.
/// - `None` — **Without Solution**: there is no precomputed solution; the author
///   chooses operator *and* target for each cage, filtered by global feasibility.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct State {
    /// Cage structure being designed.
    pub puzzle: Puzzle,
    /// The fixed Latin Square generated when the puzzle was created, or `None`
    /// in Without-Solution mode.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub solution: Option<Grid>,
    /// Working grid: cell values constrained by the current cages.
    pub current: Grid,
    /// The currently active cell.
    pub active: Cell,
    /// Provisional cage regions: disjoint from each other and from puzzle cages.
    pub provisional_cages: BTreeSet<Polyomino>,
}

impl State {
    /// Creates a new blank Without-Solution `State` for an *n*×*n* puzzle.
    ///
    /// There is no precomputed solution (`solution` is `None`) and the working
    /// grid is unconstrained.
    ///
    /// # Errors
    /// Returns an error if `n` is invalid for `Puzzle` or `Grid`.
    pub fn new(n: usize) -> Result<Self, String> {
        let puzzle = Puzzle::new(n).map_err(|e| e.to_string())?;
        let current = Grid::new(n).map_err(|e| e.to_string())?;
        Ok(Self {
            puzzle,
            solution: None,
            current,
            active: Cell::new(0, 0),
            provisional_cages: BTreeSet::new(),
        })
    }

    /// Creates a new blank With-Solution `State` for an *n*×*n* puzzle.
    ///
    /// The `solution` grid is a blank `n×n` grid; the real Latin Square is
    /// generated by the backend `new_latin_square` command. This constructor
    /// exists for tests and for transitions that need a With-Solution shape.
    ///
    /// # Errors
    /// Returns an error if `n` is invalid for `Puzzle` or `Grid`.
    pub fn new_with_solution(n: usize) -> Result<Self, String> {
        let puzzle = Puzzle::new(n).map_err(|e| e.to_string())?;
        let solution = Grid::new(n).map_err(|e| e.to_string())?;
        let current = solution.clone();
        Ok(Self {
            puzzle,
            solution: Some(solution),
            current,
            active: Cell::new(0, 0),
            provisional_cages: BTreeSet::new(),
        })
    }

    /// Switches from Without-Solution to With-Solution by snapshotting the
    /// unique completion into `solution`.
    ///
    /// # Errors
    /// Returns [`FixError::NotUnique`] if the puzzle does not have exactly one
    /// global completion, or [`FixError::Solve`] if propagation fails.
    pub fn fix(&mut self) -> Result<(), FixError> {
        let n = self.puzzle.n();
        let grid = Grid::new(n)
            .and_then(|g| g.constrain(&self.puzzle))
            .map_err(|e| FixError::Solve(e.to_string()))?;
        let mut solutions = grid.solutions(&self.puzzle);
        let first = match solutions.next() {
            Some(Ok(g)) => g,
            Some(Err(e)) => return Err(FixError::Solve(e.to_string())),
            None => return Err(FixError::NotUnique),
        };
        if solutions.next().is_some() {
            return Err(FixError::NotUnique);
        }
        drop(solutions);
        self.solution = Some(first);
        Ok(())
    }

    /// Switches from With-Solution to Without-Solution by discarding `solution`.
    ///
    /// Always succeeds — the cages were chosen against a known completion and
    /// remain globally feasible after the field is dropped.
    pub const fn unfix(&mut self) {
        self.solution = None;
    }
}

/// Error returned by [`State::fix`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FixError {
    /// The puzzle does not have exactly one global completion.
    NotUnique,
    /// Constraint propagation failed.
    Solve(String),
}

impl fmt::Display for FixError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotUnique => {
                f.write_str("cannot fix: the puzzle does not have exactly one solution")
            }
            Self::Solve(msg) => write!(f, "cannot fix: {msg}"),
        }
    }
}

impl std::error::Error for FixError {}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::{FixError, State};
    use mathdoku::{Cage, Cell, Operation, Operator, Polyomino};
    use serde_json::{from_str, to_string};

    fn cage_at(positions: &[(usize, usize)], op: Operator, target: u64) -> Cage {
        let cells: Vec<Cell> = positions.iter().map(|&(r, c)| Cell::new(r, c)).collect();
        let poly = Polyomino::from_cells(&cells).unwrap();
        Cage::new(poly, Operation::new(op, target))
    }

    #[test]
    fn new_is_without_solution() {
        let st = State::new(4).unwrap();
        assert!(st.solution.is_none());
        assert_eq!(st.puzzle.n(), 4);
    }

    #[test]
    fn new_with_solution_is_with_solution() {
        let st = State::new_with_solution(4).unwrap();
        assert!(st.solution.is_some());
    }

    #[test]
    fn unfix_drops_the_solution() {
        let mut st = State::new_with_solution(4).unwrap();
        st.unfix();
        assert!(st.solution.is_none());
    }

    /// A 3×3 puzzle pinned to the Latin square
    /// ```text
    /// 1 2 3
    /// 2 3 1
    /// 3 1 2
    /// ```
    /// by nine `Given` cages — exactly one completion.
    fn unique_3x3() -> State {
        let mut st = State::new(3).unwrap();
        let square = [[1u64, 2, 3], [2, 3, 1], [3, 1, 2]];
        for (r, row) in square.iter().enumerate() {
            for (c, &v) in row.iter().enumerate() {
                st.puzzle = st
                    .puzzle
                    .insert_cage(cage_at(&[(r, c)], Operator::Given, v))
                    .unwrap();
            }
        }
        st
    }

    #[test]
    fn fix_snapshots_unique_completion() {
        let mut st = unique_3x3();
        assert!(st.fix().is_ok());
        let solution = st.solution.unwrap();
        assert_eq!(
            solution.cell_values(Cell::new(0, 0)).unwrap().values(),
            vec![1]
        );
        assert_eq!(
            solution.cell_values(Cell::new(1, 0)).unwrap().values(),
            vec![2]
        );
    }

    #[test]
    fn fix_fails_when_not_unique() {
        // Three row-sum cages: every order-3 Latin square is a completion (12 of them).
        let mut st = State::new(3).unwrap();
        for r in 0..3 {
            st.puzzle = st
                .puzzle
                .insert_cage(cage_at(&[(r, 0), (r, 1), (r, 2)], Operator::Add, 6))
                .unwrap();
        }
        assert_eq!(st.fix(), Err(FixError::NotUnique));
        assert!(st.solution.is_none());
    }

    #[test]
    fn fix_then_unfix_round_trips_mode() {
        let mut st = unique_3x3();
        st.fix().unwrap();
        assert!(st.solution.is_some());
        st.unfix();
        assert!(st.solution.is_none());
    }

    #[test]
    fn serde_round_trip_without_solution() {
        let st = State::new(4).unwrap();
        let json = to_string(&st).unwrap();
        // The omitted-field form keeps Without-Solution JSON clean.
        assert!(!json.contains("\"solution\""));
        let restored: State = from_str(&json).unwrap();
        assert!(restored.solution.is_none());
        assert_eq!(restored.puzzle, st.puzzle);
        assert_eq!(restored.current, st.current);
        assert_eq!(restored.active, st.active);
        assert_eq!(restored.provisional_cages, st.provisional_cages);
    }

    #[test]
    fn serde_round_trip_with_solution() {
        let st = State::new_with_solution(4).unwrap();
        let json = to_string(&st).unwrap();
        assert!(json.contains("\"solution\""));
        let restored: State = from_str(&json).unwrap();
        assert!(restored.solution.is_some());
        assert_eq!(restored.puzzle, st.puzzle);
        assert_eq!(restored.solution.map(|g| g.n()), st.solution.map(|g| g.n()));
    }
}
