//! Portable core for Mathdoku Designer.
//!
//! Holds [`AppState`], the puzzle-mutation command bodies (as free functions
//! over `&mut AppState`), the serialization seam for save/load, and the serde
//! types shared with the Leptos frontend. The crate carries no dependency on
//! Tauri, so it compiles for both `wasm32-unknown-unknown` and the native
//! target.
//!
//! The native Tauri wrappers in `src-tauri` lock the `Mutex<AppState>` and
//! delegate here; a web build can own `AppState` differently (for example a
//! `thread_local!<RefCell<AppState>>`) and call the same functions, because
//! the free functions take `&mut AppState` and leave synchronization to the
//! caller.

use std::collections::{BTreeSet, HashSet};

use mathdoku::{Cage, Cell, Grid, Operation, Operator, Polyomino, Puzzle, generate_latin_square};
use rand::Rng;
use serde::{Deserialize, Serialize};
use serde_json::{from_str, to_string_pretty};

/// Serialization version written into every `.mathdoku` save file.
/// Increment when the [`SaveEnvelope`] format changes in a breaking way.
pub const SAVE_VERSION: u32 = 1;

// ---- error ----

/// Errors raised by the Designer command bodies.
///
/// Deliberately separate from [`mathdoku::Error`]: the library error describes
/// library-level operations (puzzle construction, polyomino geometry, solver
/// state) and is on track to be a public crates.io surface, whereas these
/// variants (`NoPuzzle`, `UnsupportedVersion`, …) are Designer concerns.
/// `mathdoku::Error` composes in transparently via `#[from]` so `?` works
/// inside command bodies.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error(transparent)]
    Mathdoku(#[from] mathdoku::Error),
    #[error("no puzzle loaded")]
    NoPuzzle,
    #[error("cage not found")]
    CageNotFound,
    #[error("puzzle does not have exactly one completion")]
    NotUnique,
    #[error("serialization failed: {0}")]
    Serde(String),
    #[error("unsupported save version: {0}")]
    UnsupportedVersion(u32),
}

// ---- shared IPC types ----

/// Document state returned by [`get_doc_state`].
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct DocState {
    pub dirty: bool,
    pub path: Option<String>,
}

/// Result of a save, carrying the path that was written.
#[derive(Clone, Serialize, Deserialize)]
pub struct SaveResult {
    pub path: String,
}

/// Full designer state: the unit of serialization for save files and undo/redo.
///
/// The `solution` field discriminates the two authoring modes:
///
/// - `Some(grid)` — **With Solution**: a fixed Latin Square was generated at
///   creation and cage targets are read off it.
/// - `None` — **Without Solution**: there is no precomputed solution; the author
///   chooses operator *and* target for each cage, filtered by global feasibility.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct State {
    /// Cage structure being designed.
    pub puzzle: Puzzle,
    /// The fixed Latin Square generated when the puzzle was created, or `None`
    /// in Without-Solution mode.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub solution: Option<Grid>,
    /// Working grid: cell values constrained by the current cages.
    pub current: Grid,
    /// The currently active cell.
    pub active: Cell,
    /// Provisional cages: disjoint from each other and from puzzle cages.
    pub provisional_cages: BTreeSet<Polyomino>,
}

impl State {
    /// Creates a new blank Without-Solution `State` for an *n*×*n* puzzle.
    ///
    /// There is no precomputed solution (`solution` is `None`) and the working
    /// grid is unconstrained.
    ///
    /// # Errors
    /// Returns an error if `n` is invalid for `Puzzle` or `Grid`.
    pub fn new(n: usize) -> Result<Self, String> {
        let puzzle = Puzzle::new(n).map_err(|e| e.to_string())?;
        let current = Grid::new(n).map_err(|e| e.to_string())?;
        Ok(Self {
            puzzle,
            solution: None,
            current,
            active: Cell::new(0, 0),
            provisional_cages: BTreeSet::new(),
        })
    }

    /// Creates a new blank With-Solution `State` for an *n*×*n* puzzle.
    ///
    /// The `solution` grid is a blank `n×n` grid; the real Latin Square is
    /// generated by [`new_latin_square`]. This constructor exists for tests and
    /// for transitions that need a With-Solution shape.
    ///
    /// # Errors
    /// Returns an error if `n` is invalid for `Puzzle` or `Grid`.
    pub fn new_with_solution(n: usize) -> Result<Self, String> {
        let puzzle = Puzzle::new(n).map_err(|e| e.to_string())?;
        let solution = Grid::new(n).map_err(|e| e.to_string())?;
        let current = solution.clone();
        Ok(Self {
            puzzle,
            solution: Some(solution),
            current,
            active: Cell::new(0, 0),
            provisional_cages: BTreeSet::new(),
        })
    }

    /// Switches from Without-Solution to With-Solution by snapshotting the
    /// unique completion into `solution`.
    ///
    /// # Errors
    /// Returns [`Error::NotUnique`] if the puzzle does not have exactly one
    /// global completion, or [`Error::Mathdoku`] if propagation fails.
    pub fn fix(&mut self) -> Result<(), Error> {
        let n = self.puzzle.n();
        let grid = Grid::new(n).and_then(|g| g.constrain(&self.puzzle))?;
        let mut solutions = grid.solutions(&self.puzzle);
        let first = match solutions.next() {
            Some(Ok(g)) => g,
            Some(Err(e)) => return Err(e.into()),
            None => return Err(Error::NotUnique),
        };
        if solutions.next().is_some() {
            return Err(Error::NotUnique);
        }
        drop(solutions);
        self.solution = Some(first);
        Ok(())
    }

    /// Switches from With-Solution to Without-Solution by discarding `solution`.
    ///
    /// Always succeeds — the cages were chosen against a known completion and
    /// remain globally feasible after the field is dropped.
    pub const fn unfix(&mut self) {
        self.solution = None;
    }
}

// ---- application state ----

/// Mutable backend state owned by the host (native: `Mutex<AppState>`).
///
/// All fields are `None` until a puzzle is created or loaded.
/// `solution` and `current` are always kept in sync with `puzzle`
/// by every function that mutates the puzzle.
#[derive(Default)]
pub struct AppState {
    /// Cage structure being designed.
    pub puzzle: Option<Puzzle>,
    /// Latin-square solution fixed at puzzle creation. Singleton values for every cell.
    pub solution: Option<Grid>,
    /// Working grid: cell values constrained by the current cages against the solution.
    pub current: Option<Grid>,
    /// Path of the currently open `.mathdoku` file, or `None` if unsaved.
    pub path: Option<String>,
    /// Whether the puzzle has unsaved changes.
    pub dirty: bool,
    /// Last-known active cell, persisted in `last_open.json`.
    /// `None` means (0, 0) (default when no puzzle is loaded or after a fresh load).
    pub active: Option<Cell>,
}

impl AppState {
    /// Assembles a [`State`] from the current fields, or `None` if no puzzle is loaded.
    ///
    /// A loaded puzzle requires both `puzzle` and `current`; `solution` is `None`
    /// in Without-Solution mode and passes through unchanged.
    /// `provisional_cages` is always empty — provisional state lives only in the frontend.
    fn to_designer_state(&self) -> Option<State> {
        let puzzle = self.puzzle.clone()?;
        let current = self.current.clone()?;
        Some(State {
            puzzle,
            solution: self.solution.clone(),
            current,
            active: self.active.unwrap_or_else(|| Cell::new(0, 0)),
            provisional_cages: BTreeSet::new(),
        })
    }
}

/// On-disk format for `.mathdoku` save files.
///
/// `puzzle` (the cage structure) is always persisted. `solution` (the fixed
/// Latin square) is present only for With-Solution puzzles; Without-Solution
/// puzzles omit the field, which deserializes back to `None`. Existing
/// With-Solution save files carry a non-null `solution` and load unchanged.
#[derive(Serialize, Deserialize)]
pub struct SaveEnvelope {
    pub version: u32,
    pub puzzle: Puzzle,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub solution: Option<Grid>,
}

/// Computes the working `current` grid for `puzzle`.
///
/// In With-Solution mode the cages are re-applied to the fixed Latin square so
/// its singleton values are preserved. In Without-Solution mode there is no
/// solution to start from, so the cages are propagated from a fresh
/// unconstrained grid.
///
/// # Errors
/// Returns an error if constraint propagation fails or `puzzle.n()` is invalid.
pub(crate) fn constrain_current(
    solution: Option<&Grid>,
    puzzle: &Puzzle,
) -> Result<Grid, mathdoku::Error> {
    solution.map_or_else(
        || Grid::new(puzzle.n()).and_then(|g| g.constrain(puzzle)),
        |grid| grid.constrain(puzzle),
    )
}

// ---- puzzle-mutation command bodies ----

/// Creates a new empty *n*×*n* Without-Solution puzzle with no cages and no
/// Latin-square solution.
///
/// `solution` is `None`; the author chooses operator and target for each cage,
/// filtered by global feasibility. `current` starts as an unconstrained grid.
///
/// # Errors
/// Returns an error if `n` is invalid.
pub fn new_empty(state: &mut AppState, n: usize) -> Result<State, Error> {
    let puzzle = Puzzle::new(n)?;
    let current = Grid::new(n).and_then(|g| g.constrain(&puzzle))?;
    state.puzzle = Some(puzzle);
    state.solution = None;
    state.current = Some(current);
    state.path = None;
    state.dirty = true;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

/// Creates a new puzzle whose solution is a random Latin square drawn from `rng`.
///
/// `solution` holds the fixed Latin-square values (a single value per cell).
/// `current` starts as the same Latin-square grid. Taking `rng` rather than
/// calling `rand::rng()` internally gives tests a deterministic-seed knob.
///
/// # Errors
/// Returns an error if `n` is invalid.
pub fn new_latin_square<R: Rng>(
    state: &mut AppState,
    n: usize,
    rng: &mut R,
) -> Result<State, Error> {
    let puzzle = Puzzle::new(n)?;
    let latin = generate_latin_square(n, rng);
    let solution = Grid::from_latin_square(n, &latin)?;
    let current = solution.clone();
    state.puzzle = Some(puzzle);
    state.solution = Some(solution);
    state.current = Some(current);
    state.path = None;
    state.dirty = true;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

/// Adds a cage to the current puzzle for the given cells and operator.
///
/// In Without-Solution mode the caller supplies `target` directly. In
/// With-Solution mode `target` is `None` and the value is computed from the
/// `solution` singleton values:
/// - `Given` and single-cell: the cell's solution value.
/// - `Add`: sum of all solution values.
/// - `Multiply`: product of all solution values.
/// - `Subtract` and `Divide` (2-cell only): difference or ratio of the two solution values.
///
/// Returns the updated designer `State`.
///
/// # Errors
/// Returns an error if no puzzle is loaded, the cells form an invalid polyomino,
/// or `operator` is not valid for the polyomino size.
pub fn insert_cage(
    state: &mut AppState,
    cells: &[Cell],
    operator: Operator,
    target: Option<u64>,
) -> Result<State, Error> {
    let puzzle = state.puzzle.as_ref().ok_or(Error::NoPuzzle)?;
    let poly = Polyomino::from_cells(cells)?;

    // `Some` in Without-Solution mode (author-chosen target); `None` in
    // With-Solution mode, where the target is derived from the fixed solution.
    let target = target.unwrap_or_else(|| {
        let true_values: Option<Vec<u64>> = state.solution.as_ref().and_then(|grid| {
            cells
                .iter()
                .map(|&cell| {
                    let v = grid.cell_values(cell).ok()?;
                    v.is_singleton()
                        .then(|| v.values().first().copied().map(u64::from))?
                })
                .collect()
        });
        match (&operator, true_values.as_deref()) {
            (Operator::Given, Some(vals)) => vals[0],
            (Operator::Add, Some(vals)) => vals.iter().sum(),
            (Operator::Multiply, Some(vals)) => vals.iter().product(),
            (Operator::Subtract, Some(vals)) => vals[0].abs_diff(vals[1]),
            (Operator::Divide, Some(vals)) => vals[0].max(vals[1]) / vals[0].min(vals[1]),
            _ => 0,
        }
    });
    let operation = Operation::new(operator, target);

    let cage = Cage::new(poly, operation);
    let new_puzzle = puzzle.insert_cage(cage)?;
    let new_current = constrain_current(state.solution.as_ref(), &new_puzzle)?;
    state.puzzle = Some(new_puzzle);
    state.current = Some(new_current);
    state.dirty = true;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

/// Removes the cage whose cell set matches `cells` from the current puzzle.
///
/// Returns the updated designer `State`.
///
/// # Errors
/// Returns an error if no puzzle is loaded, the cells form an invalid polyomino,
/// or no matching cage is found.
pub fn remove_cage(state: &mut AppState, cells: &[Cell]) -> Result<State, Error> {
    let puzzle = state.puzzle.as_ref().ok_or(Error::NoPuzzle)?;
    let target_cells: HashSet<_> = cells.iter().copied().collect();
    let n = puzzle.n();
    let remaining_cages: Vec<Cage> = puzzle
        .cages()
        .filter(|cage| {
            let cage_cells: HashSet<_> = cage.cells().into_iter().collect();
            cage_cells != target_cells
        })
        .cloned()
        .collect();
    if remaining_cages.len() == puzzle.cages().count() {
        return Err(Error::CageNotFound);
    }
    let new_puzzle = remaining_cages
        .into_iter()
        .try_fold(Puzzle::new(n)?, |p, cage| p.insert_cage(cage))?;
    let new_current = constrain_current(state.solution.as_ref(), &new_puzzle)?;
    state.puzzle = Some(new_puzzle);
    state.current = Some(new_current);
    state.dirty = true;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

/// Switches the current puzzle from Without-Solution to With-Solution by
/// snapshotting its unique completion into `solution`.
///
/// # Errors
/// Returns an error if no puzzle is loaded or the puzzle does not have exactly
/// one global completion.
pub fn fix(state: &mut AppState) -> Result<State, Error> {
    let mut designer = state.to_designer_state().ok_or(Error::NoPuzzle)?;
    designer.fix()?;
    state.solution.clone_from(&designer.solution);
    state.dirty = true;
    Ok(designer)
}

/// Switches the current puzzle from With-Solution to Without-Solution by
/// discarding its `solution`.
///
/// # Errors
/// Returns an error if no puzzle is loaded.
pub fn unfix(state: &mut AppState) -> Result<State, Error> {
    let mut designer = state.to_designer_state().ok_or(Error::NoPuzzle)?;
    designer.unfix();
    state.solution = None;
    state.dirty = true;
    Ok(designer)
}

/// Persists the active cell position into `state`.
pub const fn set_active_cell(state: &mut AppState, active: Cell) {
    state.active = Some(active);
}

/// Returns the document state (dirty flag and current file path).
#[must_use]
pub fn get_doc_state(state: &AppState) -> DocState {
    DocState {
        dirty: state.dirty,
        path: state.path.clone(),
    }
}

/// Returns the current designer [`State`], or `None` if no puzzle is loaded.
#[must_use]
pub fn get_puzzle(state: &AppState) -> Option<State> {
    state.to_designer_state()
}

// ---- save/load serialization seam ----

/// Serializes the current `state` into the pretty-printed [`SaveEnvelope`] JSON,
/// using the current [`SAVE_VERSION`] and field layout.
///
/// # Errors
/// Returns [`Error::NoPuzzle`] if no puzzle is loaded, or [`Error::Serde`] if
/// serialization fails.
pub fn serialize_save(state: &AppState) -> Result<String, Error> {
    let puzzle = state.puzzle.as_ref().ok_or(Error::NoPuzzle)?.clone();
    let solution = state.solution.clone();
    let envelope = SaveEnvelope {
        version: SAVE_VERSION,
        puzzle,
        solution,
    };
    to_string_pretty(&envelope).map_err(|e| Error::Serde(e.to_string()))
}

/// Parses a [`SaveEnvelope`] from `json`, version-checks it, recomputes the
/// working grid via [`constrain_current`], and writes the result into `state`.
///
/// On success the puzzle, solution, and current grid are replaced, `dirty` is
/// cleared, and `active` is reset to `None`. Returns the loaded designer
/// [`State`]. The caller is responsible for recording the file path.
///
/// # Errors
/// Returns [`Error::Serde`] if the JSON is malformed, [`Error::UnsupportedVersion`]
/// if the save version is not supported, or [`Error::Mathdoku`] if the working
/// grid cannot be reconstructed.
pub fn apply_loaded(state: &mut AppState, json: &str) -> Result<State, Error> {
    let envelope: SaveEnvelope = from_str(json).map_err(|e| Error::Serde(e.to_string()))?;
    if envelope.version != SAVE_VERSION {
        return Err(Error::UnsupportedVersion(envelope.version));
    }
    let puzzle = envelope.puzzle;
    let solution = envelope.solution;
    let current = constrain_current(solution.as_ref(), &puzzle)?;
    state.puzzle = Some(puzzle);
    state.solution = solution;
    state.current = Some(current);
    state.dirty = false;
    state.active = None;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::{
        AppState, Error, SAVE_VERSION, SaveEnvelope, State, apply_loaded, fix, get_doc_state,
        get_puzzle, insert_cage, new_empty, new_latin_square, serialize_save, unfix,
    };
    use mathdoku::{Cage, Cell, Grid, Operation, Operator, Polyomino, Puzzle};
    use serde_json::{from_str, to_string};

    fn cage_at(positions: &[(usize, usize)], op: Operator, target: u64) -> Cage {
        let cells: Vec<Cell> = positions.iter().map(|&(r, c)| Cell::new(r, c)).collect();
        let poly = Polyomino::from_cells(&cells).unwrap();
        Cage::new(poly, Operation::new(op, target))
    }

    // ---- State constructors / mode transitions ----

    #[test]
    fn new_is_without_solution() {
        let st = State::new(4).unwrap();
        assert!(st.solution.is_none());
        assert_eq!(st.puzzle.n(), 4);
    }

    #[test]
    fn new_with_solution_is_with_solution() {
        let st = State::new_with_solution(4).unwrap();
        assert!(st.solution.is_some());
    }

    #[test]
    fn unfix_drops_the_solution() {
        let mut st = State::new_with_solution(4).unwrap();
        st.unfix();
        assert!(st.solution.is_none());
    }

    /// A 3×3 puzzle pinned to the Latin square
    /// ```text
    /// 1 2 3
    /// 2 3 1
    /// 3 1 2
    /// ```
    /// by nine `Given` cages — exactly one completion.
    fn unique_3x3() -> State {
        let mut st = State::new(3).unwrap();
        let square = [[1u64, 2, 3], [2, 3, 1], [3, 1, 2]];
        for (r, row) in square.iter().enumerate() {
            for (c, &v) in row.iter().enumerate() {
                st.puzzle = st
                    .puzzle
                    .insert_cage(cage_at(&[(r, c)], Operator::Given, v))
                    .unwrap();
            }
        }
        st
    }

    #[test]
    fn fix_snapshots_unique_completion() {
        let mut st = unique_3x3();
        assert!(st.fix().is_ok());
        let solution = st.solution.unwrap();
        assert_eq!(
            solution.cell_values(Cell::new(0, 0)).unwrap().values(),
            vec![1]
        );
        assert_eq!(
            solution.cell_values(Cell::new(1, 0)).unwrap().values(),
            vec![2]
        );
    }

    #[test]
    fn fix_fails_when_not_unique() {
        // Three row-sum cages: every order-3 Latin square is a completion (12 of them).
        let mut st = State::new(3).unwrap();
        for r in 0..3 {
            st.puzzle = st
                .puzzle
                .insert_cage(cage_at(&[(r, 0), (r, 1), (r, 2)], Operator::Add, 6))
                .unwrap();
        }
        assert!(matches!(st.fix(), Err(Error::NotUnique)));
        assert!(st.solution.is_none());
    }

    #[test]
    fn fix_then_unfix_round_trips_mode() {
        let mut st = unique_3x3();
        st.fix().unwrap();
        assert!(st.solution.is_some());
        st.unfix();
        assert!(st.solution.is_none());
    }

    #[test]
    fn serde_round_trip_without_solution() {
        let st = State::new(4).unwrap();
        let json = to_string(&st).unwrap();
        // The omitted-field form keeps Without-Solution JSON clean.
        assert!(!json.contains("\"solution\""));
        let restored: State = from_str(&json).unwrap();
        assert!(restored.solution.is_none());
        assert_eq!(restored.puzzle, st.puzzle);
        assert_eq!(restored.current, st.current);
        assert_eq!(restored.active, st.active);
        assert_eq!(restored.provisional_cages, st.provisional_cages);
    }

    #[test]
    fn serde_round_trip_with_solution() {
        let st = State::new_with_solution(4).unwrap();
        let json = to_string(&st).unwrap();
        assert!(json.contains("\"solution\""));
        let restored: State = from_str(&json).unwrap();
        assert!(restored.solution.is_some());
        assert_eq!(restored.puzzle, st.puzzle);
        assert_eq!(restored.solution.map(|g| g.n()), st.solution.map(|g| g.n()));
    }

    // ---- new_empty ----

    #[test]
    fn new_empty_sets_puzzle_and_dirty() {
        let mut state = AppState::default();
        let result = new_empty(&mut state, 4).unwrap();
        assert_eq!(result.puzzle.n(), 4);
        // Without-Solution mode: no solution snapshot.
        assert!(result.solution.is_none());
        assert!(state.puzzle.is_some());
        assert!(state.solution.is_none());
        assert!(state.dirty);
        assert!(state.path.is_none());
    }

    #[test]
    fn new_empty_clears_existing_path() {
        let mut state = AppState {
            path: Some("/old/path.mathdoku".to_string()),
            ..AppState::default()
        };
        let _ = new_empty(&mut state, 4).unwrap();
        assert!(state.path.is_none());
    }

    #[test]
    fn new_empty_rejects_invalid_size() {
        let mut state = AppState::default();
        assert!(new_empty(&mut state, 0).is_err());
    }

    // ---- insert_cage target (Without-Solution mode) ----

    #[test]
    fn insert_cage_uses_author_target_without_solution() {
        let mut state = AppState::default();
        let _ = new_empty(&mut state, 4).unwrap();
        let cells = [Cell::new(0, 0), Cell::new(0, 1)];
        let st = insert_cage(&mut state, &cells, Operator::Add, Some(7)).unwrap();
        let cage = st.puzzle.cages().next().unwrap();
        assert_eq!(cage.operation().target, 7);
        assert!(st.solution.is_none());
    }

    // ---- fix / unfix ----

    #[test]
    fn fix_errs_when_not_unique() {
        let mut state = AppState::default();
        // An empty 3×3 Without-Solution puzzle has many completions.
        let _ = new_empty(&mut state, 3).unwrap();
        assert!(fix(&mut state).is_err());
    }

    #[test]
    fn unfix_clears_solution() {
        let mut state = AppState::default();
        let _ = new_latin_square(&mut state, 3, &mut rand::rng()).unwrap();
        let st = unfix(&mut state).unwrap();
        assert!(st.solution.is_none());
        assert!(state.solution.is_none());
    }

    // ---- get_doc_state ----

    #[test]
    fn get_doc_state_returns_current_values() {
        let state = AppState {
            dirty: true,
            path: Some("/some/path.mathdoku".to_string()),
            ..AppState::default()
        };
        let doc = get_doc_state(&state);
        assert!(doc.dirty);
        assert_eq!(doc.path.as_deref(), Some("/some/path.mathdoku"));
    }

    #[test]
    fn get_doc_state_default_is_clean_with_no_path() {
        let state = AppState::default();
        let doc = get_doc_state(&state);
        assert!(!doc.dirty);
        assert!(doc.path.is_none());
    }

    // ---- get_puzzle ----

    #[test]
    fn get_puzzle_returns_none_when_no_puzzle() {
        let state = AppState::default();
        assert!(get_puzzle(&state).is_none());
    }

    #[test]
    fn get_puzzle_returns_puzzle_when_loaded() {
        let mut state = AppState::default();
        let _ = new_empty(&mut state, 6).unwrap();
        let p = get_puzzle(&state).unwrap();
        assert_eq!(p.puzzle.n(), 6);
    }

    // ---- serialize_save / apply_loaded seam ----

    #[test]
    fn serialize_save_apply_loaded_round_trips() {
        let state = AppState {
            puzzle: Some(Puzzle::new(5).unwrap()),
            current: Some(Grid::new(5).unwrap()),
            ..AppState::default()
        };
        let json = serialize_save(&state).unwrap();

        let mut loaded = AppState::default();
        let designer = apply_loaded(&mut loaded, &json).unwrap();
        assert_eq!(designer.puzzle.n(), 5);
        assert!(!loaded.dirty);
        assert!(loaded.active.is_none());
        assert_eq!(loaded.puzzle.unwrap().n(), 5);
    }

    #[test]
    fn serialize_save_errors_when_no_puzzle() {
        let state = AppState::default();
        assert!(matches!(serialize_save(&state), Err(Error::NoPuzzle)));
    }

    #[test]
    fn apply_loaded_rejects_wrong_version() {
        let envelope = SaveEnvelope {
            version: 99,
            puzzle: Puzzle::new(3).unwrap(),
            solution: None,
        };
        let json = to_string(&envelope).unwrap();
        let mut state = AppState::default();
        assert!(matches!(
            apply_loaded(&mut state, &json),
            Err(Error::UnsupportedVersion(99))
        ));
    }

    #[test]
    fn apply_loaded_rejects_malformed_json() {
        let mut state = AppState::default();
        assert!(matches!(
            apply_loaded(&mut state, "not json"),
            Err(Error::Serde(_))
        ));
    }

    #[test]
    fn save_version_is_one() {
        assert_eq!(SAVE_VERSION, 1);
    }
}
