//! Portable core for Mathdoku Designer.
//!
//! Holds [`AppState`], the puzzle-mutation command bodies (as free functions
//! over `&mut AppState`), the serialization seam for save/load, and the serde
//! types shared with the Leptos frontend. The crate carries no dependency on
//! Tauri, so it compiles for both `wasm32-unknown-unknown` and the native
//! target.
//!
//! The native Tauri wrappers in `src-tauri` lock the `Mutex<AppState>` and
//! delegate here; a web build can own `AppState` differently (for example a
//! `thread_local!<RefCell<AppState>>`) and call the same functions, because
//! the free functions take `&mut AppState` and leave synchronization to the
//! caller.

use std::collections::BTreeSet;

use mathdoku::{Cage, Cell, Grid, Operation, Operator, Polyomino, Puzzle, generate_latin_square};
use rand::Rng;
use serde::{Deserialize, Serialize};
use serde_json::{from_str, to_string_pretty};

/// Serialization version written into every `.mathdoku` save file.
/// Increment when the [`SaveEnvelope`] format changes in a breaking way.
pub const SAVE_VERSION: u32 = 1;

// ---- error ----

/// Errors raised by the Designer command bodies.
///
/// Deliberately separate from [`mathdoku::Error`]: the library error describes
/// library-level operations (puzzle construction, polyomino geometry, solver
/// state) and is on track to be a public crates.io surface, whereas these
/// variants (`NoPuzzle`, `UnsupportedVersion`, …) are Designer concerns.
/// `mathdoku::Error` composes in transparently via `#[from]` so `?` works
/// inside command bodies.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error(transparent)]
    Mathdoku(#[from] mathdoku::Error),
    #[error("no puzzle loaded")]
    NoPuzzle,
    #[error("cage not found")]
    CageNotFound,
    #[error("puzzle does not have exactly one completion")]
    NotUnique,
    #[error("serialization failed: {0}")]
    Serde(String),
    #[error("unsupported save version: {0}")]
    UnsupportedVersion(u32),
}

// ---- shared IPC types ----

/// Document state returned by [`get_doc_state`].
#[derive(Clone, Default, Serialize, Deserialize)]
pub struct DocState {
    pub dirty: bool,
    pub path: Option<String>,
}

/// Result of a save, carrying the path that was written.
#[derive(Clone, Serialize, Deserialize)]
pub struct SaveResult {
    pub path: String,
}

/// Full designer state: the unit of serialization for save files and undo/redo.
///
/// The `solution` field discriminates the two authoring modes:
///
/// - `Some(grid)` — **With Solution**: a fixed Latin Square was generated at
///   creation and cage targets are read off it.
/// - `None` — **Without Solution**: there is no precomputed solution; the author
///   chooses operator *and* target for each cage, filtered by global feasibility.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct State {
    /// Cage structure being designed.
    pub puzzle: Puzzle,
    /// The fixed Latin Square generated when the puzzle was created, or `None`
    /// in Without-Solution mode.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub solution: Option<Grid>,
    /// Working grid: cell values constrained by the current cages.
    pub current: Grid,
    /// The currently active cell.
    pub active: Cell,
    /// Provisional cages: disjoint from each other and from puzzle cages.
    pub provisional_cages: BTreeSet<Polyomino>,
}

impl State {
    /// Creates a new blank Without-Solution `State` for an *n*×*n* puzzle.
    ///
    /// There is no precomputed solution (`solution` is `None`) and the working
    /// grid is unconstrained.
    ///
    /// # Errors
    /// Returns an error if `n` is invalid for `Puzzle` or `Grid`.
    pub fn new(n: usize) -> Result<Self, String> {
        let puzzle = Puzzle::new(n).map_err(|e| e.to_string())?;
        let current = Grid::new(n).map_err(|e| e.to_string())?;
        Ok(Self {
            puzzle,
            solution: None,
            current,
            active: Cell::new(0, 0),
            provisional_cages: BTreeSet::new(),
        })
    }

    /// Creates a new blank With-Solution `State` for an *n*×*n* puzzle.
    ///
    /// The `solution` grid is a blank `n×n` grid; the real Latin Square is
    /// generated by [`new_latin_square`]. This constructor exists for tests and
    /// for transitions that need a With-Solution shape.
    ///
    /// # Errors
    /// Returns an error if `n` is invalid for `Puzzle` or `Grid`.
    pub fn new_with_solution(n: usize) -> Result<Self, String> {
        let puzzle = Puzzle::new(n).map_err(|e| e.to_string())?;
        let solution = Grid::new(n).map_err(|e| e.to_string())?;
        let current = solution.clone();
        Ok(Self {
            puzzle,
            solution: Some(solution),
            current,
            active: Cell::new(0, 0),
            provisional_cages: BTreeSet::new(),
        })
    }

    /// Switches from Without-Solution to With-Solution by snapshotting the
    /// unique completion into `solution`.
    ///
    /// # Errors
    /// Returns [`Error::NotUnique`] if the puzzle does not have exactly one
    /// global completion, or [`Error::Mathdoku`] if propagation fails.
    pub fn fix(&mut self) -> Result<(), Error> {
        let n = self.puzzle.n();
        let grid = Grid::new(n).and_then(|g| g.constrain(&self.puzzle))?;
        let mut solutions = grid.solutions(&self.puzzle);
        let first = match solutions.next() {
            Some(Ok(g)) => g,
            Some(Err(e)) => return Err(e.into()),
            None => return Err(Error::NotUnique),
        };
        if solutions.next().is_some() {
            return Err(Error::NotUnique);
        }
        drop(solutions);
        self.solution = Some(first);
        Ok(())
    }

    /// Switches from With-Solution to Without-Solution by discarding `solution`.
    ///
    /// Always succeeds — the cages were chosen against a known completion and
    /// remain globally feasible after the field is dropped.
    pub const fn unfix(&mut self) {
        self.solution = None;
    }
}

// ---- application state ----

/// Mutable backend state owned by the host (native: `Mutex<AppState>`).
///
/// All fields are `None` until a puzzle is created or loaded.
/// `solution` and `current` are always kept in sync with `puzzle`
/// by every function that mutates the puzzle.
#[derive(Default)]
pub struct AppState {
    /// Cage structure being designed.
    pub puzzle: Option<Puzzle>,
    /// Latin-square solution fixed at puzzle creation. Singleton values for every cell.
    pub solution: Option<Grid>,
    /// Working grid: cell values constrained by the current cages against the solution.
    pub current: Option<Grid>,
    /// Path of the currently open `.mathdoku` file, or `None` if unsaved.
    pub path: Option<String>,
    /// Whether the puzzle has unsaved changes.
    pub dirty: bool,
    /// Last-known active cell, persisted in `last_open.json`.
    /// `None` means (0, 0) (default when no puzzle is loaded or after a fresh load).
    pub active: Option<Cell>,
}

impl AppState {
    /// Assembles a [`State`] from the current fields, or `None` if no puzzle is loaded.
    ///
    /// A loaded puzzle requires both `puzzle` and `current`; `solution` is `None`
    /// in Without-Solution mode and passes through unchanged.
    /// `provisional_cages` is always empty — provisional state lives only in the frontend.
    fn to_designer_state(&self) -> Option<State> {
        let puzzle = self.puzzle.clone()?;
        let current = self.current.clone()?;
        Some(State {
            puzzle,
            solution: self.solution.clone(),
            current,
            active: self.active.unwrap_or_else(|| Cell::new(0, 0)),
            provisional_cages: BTreeSet::new(),
        })
    }
}

/// On-disk format for `.mathdoku` save files.
///
/// `puzzle` (the cage structure) is always persisted. `solution` (the fixed
/// Latin square) is present only for With-Solution puzzles; Without-Solution
/// puzzles omit the field, which deserializes back to `None`. Existing
/// With-Solution save files carry a non-null `solution` and load unchanged.
#[derive(Serialize, Deserialize)]
pub struct SaveEnvelope {
    pub version: u32,
    pub puzzle: Puzzle,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub solution: Option<Grid>,
}

/// Computes the working `current` grid for `puzzle`.
///
/// In With-Solution mode the cages are re-applied to the fixed Latin square so
/// its singleton values are preserved. In Without-Solution mode there is no
/// solution to start from, so the cages are propagated from a fresh
/// unconstrained grid.
///
/// # Errors
/// Returns an error if constraint propagation fails or `puzzle.n()` is invalid.
pub(crate) fn constrain_current(
    solution: Option<&Grid>,
    puzzle: &Puzzle,
) -> Result<Grid, mathdoku::Error> {
    solution.map_or_else(
        || Grid::new(puzzle.n()).and_then(|g| g.constrain(puzzle)),
        |grid| grid.constrain(puzzle),
    )
}

// ---- puzzle-mutation command bodies ----

/// Stores `new_puzzle` and its re-constrained grid into `state`, marks dirty,
/// and returns the updated designer state. Shared tail of `insert_cage` and
/// `remove_cage_at`.
fn commit_puzzle(state: &mut AppState, new_puzzle: Puzzle) -> Result<State, Error> {
    let new_current = constrain_current(state.solution.as_ref(), &new_puzzle)?;
    state.puzzle = Some(new_puzzle);
    state.current = Some(new_current);
    state.dirty = true;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

/// Creates a new empty *n*×*n* Without-Solution puzzle with no cages and no
/// Latin-square solution.
///
/// `solution` is `None`; the author chooses operator and target for each cage,
/// filtered by global feasibility. `current` starts as an unconstrained grid.
///
/// # Errors
/// Returns an error if `n` is invalid.
pub fn new_empty(state: &mut AppState, n: usize) -> Result<State, Error> {
    let puzzle = Puzzle::new(n)?;
    let current = Grid::new(n).and_then(|g| g.constrain(&puzzle))?;
    state.puzzle = Some(puzzle);
    state.solution = None;
    state.current = Some(current);
    state.path = None;
    state.dirty = true;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

/// Creates a new puzzle whose solution is a random Latin square drawn from `rng`.
///
/// `solution` holds the fixed Latin-square values (a single value per cell).
/// `current` starts as the same Latin-square grid. Taking `rng` rather than
/// calling `rand::rng()` internally gives tests a deterministic-seed knob.
///
/// # Errors
/// Returns an error if `n` is invalid.
pub fn new_latin_square<R: Rng>(
    state: &mut AppState,
    n: usize,
    rng: &mut R,
) -> Result<State, Error> {
    let puzzle = Puzzle::new(n)?;
    let latin = generate_latin_square(n, rng);
    let solution = Grid::from_latin_square(n, &latin)?;
    let current = solution.clone();
    state.puzzle = Some(puzzle);
    state.solution = Some(solution);
    state.current = Some(current);
    state.path = None;
    state.dirty = true;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

/// Adds a cage to the current puzzle for the given cells and operator.
///
/// In Without-Solution mode the caller supplies `target` directly. In
/// With-Solution mode `target` is `None` and the value is computed from the
/// `solution` singleton values:
/// - `Given` and single-cell: the cell's solution value.
/// - `Add`: sum of all solution values.
/// - `Multiply`: product of all solution values.
/// - `Subtract` and `Divide` (2-cell only): difference or ratio of the two solution values.
///
/// Returns the updated designer `State`.
///
/// # Errors
/// Returns an error if no puzzle is loaded, the cells form an invalid polyomino,
/// or `operator` is not valid for the polyomino size.
pub fn insert_cage(
    state: &mut AppState,
    cells: &[Cell],
    operator: Operator,
    target: Option<u64>,
) -> Result<State, Error> {
    let puzzle = state.puzzle.as_ref().ok_or(Error::NoPuzzle)?;
    let poly = Polyomino::from_cells(cells)?;

    // `Some` in Without-Solution mode (author-chosen target); `None` in
    // With-Solution mode, where the target is derived from the fixed solution.
    let target = target.unwrap_or_else(|| {
        let true_values: Option<Vec<u64>> = state.solution.as_ref().and_then(|grid| {
            cells
                .iter()
                .map(|&cell| {
                    let v = grid.cell_values(cell).ok()?;
                    v.is_singleton()
                        .then(|| v.values().first().copied().map(u64::from))?
                })
                .collect()
        });
        match (&operator, true_values.as_deref()) {
            (Operator::Given, Some(vals)) => vals[0],
            (Operator::Add, Some(vals)) => vals.iter().sum(),
            (Operator::Multiply, Some(vals)) => vals.iter().product(),
            (Operator::Subtract, Some(vals)) => vals[0].abs_diff(vals[1]),
            (Operator::Divide, Some(vals)) => vals[0].max(vals[1]) / vals[0].min(vals[1]),
            _ => 0,
        }
    });
    let operation = Operation::new(operator, target);

    let cage = Cage::new(poly, operation)?;
    let new_puzzle = puzzle.insert_cage(cage)?;
    commit_puzzle(state, new_puzzle)
}

/// Removes the cage covering `polyomino` from the current puzzle.
///
/// Returns the updated designer `State`.
///
/// # Errors
/// Returns an error if no puzzle is loaded or no cage covers exactly `polyomino`.
pub fn remove_cage_at(state: &mut AppState, polyomino: &Polyomino) -> Result<State, Error> {
    let puzzle = state.puzzle.as_ref().ok_or(Error::NoPuzzle)?;
    let cage = puzzle
        .get_cage_at(polyomino)
        .ok_or(Error::CageNotFound)?
        .clone();
    let new_puzzle = puzzle.remove_cage(&cage);
    commit_puzzle(state, new_puzzle)
}

/// Switches the current puzzle from Without-Solution to With-Solution by
/// snapshotting its unique completion into `solution`.
///
/// # Errors
/// Returns an error if no puzzle is loaded or the puzzle does not have exactly
/// one global completion.
pub fn fix(state: &mut AppState) -> Result<State, Error> {
    let mut designer = state.to_designer_state().ok_or(Error::NoPuzzle)?;
    designer.fix()?;
    state.solution.clone_from(&designer.solution);
    state.dirty = true;
    Ok(designer)
}

/// Switches the current puzzle from With-Solution to Without-Solution by
/// discarding its `solution`.
///
/// # Errors
/// Returns an error if no puzzle is loaded.
pub fn unfix(state: &mut AppState) -> Result<State, Error> {
    let mut designer = state.to_designer_state().ok_or(Error::NoPuzzle)?;
    designer.unfix();
    state.solution = None;
    state.dirty = true;
    Ok(designer)
}

/// Persists the active cell position into `state`.
pub const fn set_active_cell(state: &mut AppState, active: Cell) {
    state.active = Some(active);
}

/// Returns the document state (dirty flag and current file path).
#[must_use]
pub fn get_doc_state(state: &AppState) -> DocState {
    DocState {
        dirty: state.dirty,
        path: state.path.clone(),
    }
}

/// Returns the current designer [`State`], or `None` if no puzzle is loaded.
#[must_use]
pub fn get_puzzle(state: &AppState) -> Option<State> {
    state.to_designer_state()
}

// ---- save/load serialization seam ----

/// Serializes the current `state` into the pretty-printed [`SaveEnvelope`] JSON,
/// using the current [`SAVE_VERSION`] and field layout.
///
/// # Errors
/// Returns [`Error::NoPuzzle`] if no puzzle is loaded, or [`Error::Serde`] if
/// serialization fails.
pub fn serialize_save(state: &AppState) -> Result<String, Error> {
    let puzzle = state.puzzle.as_ref().ok_or(Error::NoPuzzle)?.clone();
    let solution = state.solution.clone();
    let envelope = SaveEnvelope {
        version: SAVE_VERSION,
        puzzle,
        solution,
    };
    to_string_pretty(&envelope).map_err(|e| Error::Serde(e.to_string()))
}

/// Parses a [`SaveEnvelope`] from `json`, version-checks it, recomputes the
/// working grid via [`constrain_current`], and writes the result into `state`.
///
/// On success the puzzle, solution, and current grid are replaced, `dirty` is
/// cleared, and `active` is reset to `None`. Returns the loaded designer
/// [`State`]. The caller is responsible for recording the file path.
///
/// # Errors
/// Returns [`Error::Serde`] if the JSON is malformed, [`Error::UnsupportedVersion`]
/// if the save version is not supported, or [`Error::Mathdoku`] if the working
/// grid cannot be reconstructed.
pub fn apply_loaded(state: &mut AppState, json: &str) -> Result<State, Error> {
    let envelope: SaveEnvelope = from_str(json).map_err(|e| Error::Serde(e.to_string()))?;
    if envelope.version != SAVE_VERSION {
        return Err(Error::UnsupportedVersion(envelope.version));
    }
    let puzzle = envelope.puzzle;
    let solution = envelope.solution;
    let current = constrain_current(solution.as_ref(), &puzzle)?;
    state.puzzle = Some(puzzle);
    state.solution = solution;
    state.current = Some(current);
    state.dirty = false;
    state.active = None;
    state.to_designer_state().ok_or(Error::NoPuzzle)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic, clippy::cast_possible_truncation)]
mod tests {
    //! Tests for the Designer command bodies.
    //!
    //! Organized into named submodules by concern. The 23 tests migrated in #47
    //! keep their original names (now nested under a submodule) and remain
    //! searchable.
    //!
    //! Several tests assert *current* behaviour that diverges from #55's stated
    //! expectation; each is marked `// TODO(#NN)` against the tracking issue.
    //! Per #55 this PR is tests-only and does not fix the underlying behaviour.

    /// Shared fixtures.
    mod helpers {
        use crate::{AppState, State, apply_loaded, insert_cage, new_empty, serialize_save};
        use mathdoku::{Cage, Cell, Grid, Operation, Operator, Polyomino, Puzzle};

        /// Builds a [`Cage`] from `(row, column)` positions, an operator, and a target.
        pub(super) fn cage_at(positions: &[(usize, usize)], op: Operator, target: u64) -> Cage {
            let cells: Vec<Cell> = positions.iter().map(|&(r, c)| Cell::new(r, c)).collect();
            let poly = Polyomino::from_cells(&cells).unwrap();
            Cage::new(poly, Operation::new(op, target)).unwrap()
        }

        /// Builds [`Cell`]s from `(row, column)` positions.
        pub(super) fn cells(positions: &[(usize, usize)]) -> Vec<Cell> {
            positions.iter().map(|&(r, c)| Cell::new(r, c)).collect()
        }

        /// Every cell of an `n`×`n` grid in row-major order.
        pub(super) fn all_cells(n: usize) -> Vec<Cell> {
            (0..n)
                .flat_map(|r| (0..n).map(move |c| Cell::new(r, c)))
                .collect()
        }

        /// A 3×3 puzzle pinned to the Latin square
        /// ```text
        /// 1 2 3
        /// 2 3 1
        /// 3 1 2
        /// ```
        /// by nine `Given` cages — exactly one completion.
        pub(super) fn unique_3x3() -> State {
            let mut st = State::new(3).unwrap();
            let square = [[1u64, 2, 3], [2, 3, 1], [3, 1, 2]];
            for (r, row) in square.iter().enumerate() {
                for (c, &v) in row.iter().enumerate() {
                    st.puzzle = st
                        .puzzle
                        .insert_cage(cage_at(&[(r, c)], Operator::Given, v))
                        .unwrap();
                }
            }
            st
        }

        /// The canonical 3×3 Latin square used by the target-derivation tests:
        /// ```text
        /// 1 2 3
        /// 2 3 1
        /// 3 1 2
        /// ```
        pub(super) fn known_3x3_solution() -> Grid {
            let square = vec![vec![1u8, 2, 3], vec![2, 3, 1], vec![3, 1, 2]];
            Grid::from_latin_square(3, &square).unwrap()
        }

        /// A With-Solution [`AppState`] whose solution is [`known_3x3_solution`]
        /// and whose puzzle has no cages yet.
        pub(super) fn with_solution_3x3() -> AppState {
            let solution = known_3x3_solution();
            AppState {
                puzzle: Some(Puzzle::new(3).unwrap()),
                solution: Some(solution.clone()),
                current: Some(solution),
                ..AppState::default()
            }
        }

        /// A fresh Without-Solution `n`×`n` [`AppState`].
        pub(super) fn without_solution(n: usize) -> AppState {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, n).unwrap();
            state
        }

        /// A 3×3 [`AppState`] pinned to the same Latin square as [`unique_3x3`]
        /// by nine `Given` cages — exactly one completion.
        pub(super) fn unique_3x3_app_state() -> AppState {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 3).unwrap();
            let square = [[1u64, 2, 3], [2, 3, 1], [3, 1, 2]];
            for (r, row) in square.iter().enumerate() {
                for (c, &v) in row.iter().enumerate() {
                    let _ = insert_cage(&mut state, &cells(&[(r, c)]), Operator::Given, Some(v))
                        .unwrap();
                }
            }
            state
        }

        /// Serializes `source`, loads it into a fresh state, and returns the loaded state.
        pub(super) fn save_round_trip(source: &AppState) -> AppState {
            let json = serialize_save(source).unwrap();
            let mut loaded = AppState::default();
            let _ = apply_loaded(&mut loaded, &json).unwrap();
            loaded
        }
    }

    // ---- State constructors / mode transitions (migrated from #47) ----

    mod state_transitions {
        use super::helpers::{cage_at, unique_3x3};
        use crate::{Error, State};
        use mathdoku::{Cell, Operator};
        use serde_json::{from_str, to_string};

        #[test]
        fn new_is_without_solution() {
            let st = State::new(4).unwrap();
            assert!(st.solution.is_none());
            assert_eq!(st.puzzle.n(), 4);
        }

        #[test]
        fn new_with_solution_is_with_solution() {
            let st = State::new_with_solution(4).unwrap();
            assert!(st.solution.is_some());
        }

        #[test]
        fn unfix_drops_the_solution() {
            let mut st = State::new_with_solution(4).unwrap();
            st.unfix();
            assert!(st.solution.is_none());
        }

        #[test]
        fn fix_snapshots_unique_completion() {
            let mut st = unique_3x3();
            assert!(st.fix().is_ok());
            let solution = st.solution.unwrap();
            assert_eq!(
                solution.cell_values(Cell::new(0, 0)).unwrap().values(),
                vec![1]
            );
            assert_eq!(
                solution.cell_values(Cell::new(1, 0)).unwrap().values(),
                vec![2]
            );
        }

        #[test]
        fn fix_fails_when_not_unique() {
            // Three row-sum cages: every order-3 Latin square is a completion (12 of them).
            let mut st = State::new(3).unwrap();
            for r in 0..3 {
                st.puzzle = st
                    .puzzle
                    .insert_cage(cage_at(&[(r, 0), (r, 1), (r, 2)], Operator::Add, 6))
                    .unwrap();
            }
            assert!(matches!(st.fix(), Err(Error::NotUnique)));
            assert!(st.solution.is_none());
        }

        #[test]
        fn fix_then_unfix_round_trips_mode() {
            let mut st = unique_3x3();
            st.fix().unwrap();
            assert!(st.solution.is_some());
            st.unfix();
            assert!(st.solution.is_none());
        }

        #[test]
        fn serde_round_trip_without_solution() {
            let st = State::new(4).unwrap();
            let json = to_string(&st).unwrap();
            // The omitted-field form keeps Without-Solution JSON clean.
            assert!(!json.contains("\"solution\""));
            let restored: State = from_str(&json).unwrap();
            assert!(restored.solution.is_none());
            assert_eq!(restored.puzzle, st.puzzle);
            assert_eq!(restored.current, st.current);
            assert_eq!(restored.active, st.active);
            assert_eq!(restored.provisional_cages, st.provisional_cages);
        }

        #[test]
        fn serde_round_trip_with_solution() {
            let st = State::new_with_solution(4).unwrap();
            let json = to_string(&st).unwrap();
            assert!(json.contains("\"solution\""));
            let restored: State = from_str(&json).unwrap();
            assert!(restored.solution.is_some());
            assert_eq!(restored.puzzle, st.puzzle);
            assert_eq!(restored.solution.map(|g| g.n()), st.solution.map(|g| g.n()));
        }
    }

    // ---- Category 1: command-body error paths ----

    mod command_errors {
        use super::helpers::cells;
        use crate::{
            AppState, Error, SaveEnvelope, apply_loaded, fix, insert_cage, new_empty,
            new_latin_square, remove_cage_at, serialize_save, unfix,
        };
        use mathdoku::{Cell, Operator, Polyomino, Puzzle};
        use rand::{SeedableRng, rngs::StdRng};
        use serde_json::to_string;

        // --- insert_cage ---

        #[test]
        fn insert_cage_no_puzzle_errors() {
            let mut state = AppState::default();
            let r = insert_cage(&mut state, &[Cell::new(0, 0)], Operator::Given, Some(1));
            assert!(matches!(r, Err(Error::NoPuzzle)));
        }

        #[test]
        fn insert_cage_disconnected_polyomino_is_mathdoku_error() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let r = insert_cage(
                &mut state,
                &cells(&[(0, 0), (2, 2)]),
                Operator::Add,
                Some(3),
            );
            assert!(matches!(
                r,
                Err(Error::Mathdoku(mathdoku::Error::DisconnectedPolyomino))
            ));
        }

        #[test]
        fn insert_cage_overlap_is_cage_conflict() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let _ = insert_cage(
                &mut state,
                &cells(&[(0, 0), (0, 1)]),
                Operator::Add,
                Some(3),
            )
            .unwrap();
            let r = insert_cage(&mut state, &cells(&[(0, 0)]), Operator::Given, Some(1));
            // An overlapping region surfaces as the mathdoku-level `CageConflict`.
            assert!(matches!(
                r,
                Err(Error::Mathdoku(mathdoku::Error::CageConflict(_)))
            ));
        }

        #[test]
        fn insert_cage_subtract_on_three_cells_returns_err() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let region = cells(&[(0, 0), (0, 1), (0, 2)]);
            assert!(matches!(
                insert_cage(&mut state, &region, Operator::Subtract, Some(1)),
                Err(Error::Mathdoku(mathdoku::Error::InfeasibleOperation(_, _)))
            ));
        }

        #[test]
        fn insert_cage_given_on_two_cells_returns_err() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let region = cells(&[(0, 0), (0, 1)]);
            assert!(matches!(
                insert_cage(&mut state, &region, Operator::Given, Some(2)),
                Err(Error::Mathdoku(mathdoku::Error::InfeasibleOperation(_, _)))
            ));
        }

        #[test]
        fn insert_cage_infeasible_target_currently_succeeds() {
            // TODO(#68): #55 expects Err(InfeasibleOperation). Two distinct
            // collinear cells cannot sum to 2, but insert_cage commits the cage
            // and prunes the cells to empty domains.
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 3).unwrap();
            let region = cells(&[(0, 0), (0, 1)]);
            let st = insert_cage(&mut state, &region, Operator::Add, Some(2)).unwrap();
            assert!(st.current.cell_values(region[0]).unwrap().is_empty());
        }

        // --- remove_cage_at ---

        fn poly(positions: &[(usize, usize)]) -> Polyomino {
            Polyomino::from_cells(&cells(positions)).unwrap()
        }

        #[test]
        fn remove_cage_at_no_puzzle_errors() {
            let mut state = AppState::default();
            assert!(matches!(
                remove_cage_at(&mut state, &poly(&[(0, 0)])),
                Err(Error::NoPuzzle)
            ));
        }

        #[test]
        fn remove_cage_at_unknown_polyomino_is_cage_not_found() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let _ = insert_cage(&mut state, &cells(&[(0, 0)]), Operator::Given, Some(1)).unwrap();
            assert!(matches!(
                remove_cage_at(&mut state, &poly(&[(1, 1)])),
                Err(Error::CageNotFound)
            ));
        }

        // --- fix ---

        #[test]
        fn fix_no_puzzle_errors() {
            let mut state = AppState::default();
            assert!(matches!(fix(&mut state), Err(Error::NoPuzzle)));
        }

        #[test]
        fn fix_errs_when_not_unique() {
            let mut state = AppState::default();
            // An empty 3×3 Without-Solution puzzle has many completions.
            let _ = new_empty(&mut state, 3).unwrap();
            assert!(fix(&mut state).is_err());
        }

        #[test]
        fn fix_zero_completions_is_not_unique() {
            // Over-constrained: two `Given` cells in the same row both fixed to 1
            // admits no completion. `fix` requires exactly one, so it reports
            // NotUnique (confirming the "exactly one completion" wording covers
            // the zero-completion case too).
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 3).unwrap();
            let _ = insert_cage(&mut state, &cells(&[(0, 0)]), Operator::Given, Some(1)).unwrap();
            let _ = insert_cage(&mut state, &cells(&[(0, 1)]), Operator::Given, Some(1)).unwrap();
            assert!(matches!(fix(&mut state), Err(Error::NotUnique)));
        }

        #[test]
        fn fix_multiple_completions_is_not_unique() {
            // A higher-arity row-sum cage on a 4×4 still leaves many completions.
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let _ = insert_cage(
                &mut state,
                &cells(&[(0, 0), (0, 1), (0, 2), (0, 3)]),
                Operator::Add,
                Some(10),
            )
            .unwrap();
            assert!(matches!(fix(&mut state), Err(Error::NotUnique)));
        }

        // --- unfix ---

        #[test]
        fn unfix_no_puzzle_errors() {
            let mut state = AppState::default();
            assert!(matches!(unfix(&mut state), Err(Error::NoPuzzle)));
        }

        #[test]
        fn unfix_on_without_solution_is_idempotent() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            assert!(state.solution.is_none());
            let st = unfix(&mut state).unwrap();
            assert!(st.solution.is_none());
            assert!(state.solution.is_none());
        }

        // --- new_empty / new_latin_square invalid sizes ---

        #[test]
        fn new_empty_rejects_invalid_size() {
            let mut state = AppState::default();
            assert!(new_empty(&mut state, 0).is_err());
        }

        #[test]
        fn new_empty_rejects_n_too_large() {
            let mut state = AppState::default();
            assert!(matches!(
                new_empty(&mut state, 10),
                Err(Error::Mathdoku(mathdoku::Error::InvalidGridSize(10)))
            ));
        }

        #[test]
        fn new_latin_square_rejects_zero() {
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(1);
            assert!(matches!(
                new_latin_square(&mut state, 0, &mut rng),
                Err(Error::Mathdoku(mathdoku::Error::InvalidGridSize(0)))
            ));
        }

        #[test]
        fn new_latin_square_rejects_n_too_large() {
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(1);
            assert!(matches!(
                new_latin_square(&mut state, 10, &mut rng),
                Err(Error::Mathdoku(mathdoku::Error::InvalidGridSize(10)))
            ));
        }

        // --- serialize_save / apply_loaded ---

        #[test]
        fn serialize_save_errors_when_no_puzzle() {
            let state = AppState::default();
            assert!(matches!(serialize_save(&state), Err(Error::NoPuzzle)));
        }

        #[test]
        fn serialize_save_succeeds_after_unfix() {
            // After a With-Solution puzzle is unfixed, serialize_save still works
            // and omits the (now-absent) solution key.
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(3);
            let _ = new_latin_square(&mut state, 3, &mut rng).unwrap();
            let _ = unfix(&mut state).unwrap();
            let json = serialize_save(&state).unwrap();
            assert!(!json.contains("\"solution\""));
        }

        #[test]
        fn apply_loaded_rejects_wrong_version() {
            let envelope = SaveEnvelope {
                version: 99,
                puzzle: Puzzle::new(3).unwrap(),
                solution: None,
            };
            let json = to_string(&envelope).unwrap();
            let mut state = AppState::default();
            assert!(matches!(
                apply_loaded(&mut state, &json),
                Err(Error::UnsupportedVersion(99))
            ));
        }

        #[test]
        fn apply_loaded_rejects_version_zero() {
            let envelope = SaveEnvelope {
                version: 0,
                puzzle: Puzzle::new(3).unwrap(),
                solution: None,
            };
            let json = to_string(&envelope).unwrap();
            let mut state = AppState::default();
            assert!(matches!(
                apply_loaded(&mut state, &json),
                Err(Error::UnsupportedVersion(0))
            ));
        }

        #[test]
        fn apply_loaded_rejects_malformed_json() {
            let mut state = AppState::default();
            assert!(matches!(
                apply_loaded(&mut state, "not json"),
                Err(Error::Serde(_))
            ));
        }

        #[test]
        fn apply_loaded_out_of_bounds_cage_cell_is_invalid_cell() {
            // #55 guessed `Serde`, but a syntactically valid envelope whose cage
            // references a cell outside the grid parses fine and is caught during
            // constraint propagation — surfacing as Mathdoku(InvalidCell), the
            // correct behaviour.
            let json = r#"{"version":1,"puzzle":{"n":3,"cages":[{"polyomino":[{"row":5,"column":5}],"operation":{"operator":"Given","target":1}}]}}"#;
            let mut state = AppState::default();
            assert!(matches!(
                apply_loaded(&mut state, json),
                Err(Error::Mathdoku(mathdoku::Error::InvalidCell(_)))
            ));
        }

        #[test]
        fn apply_loaded_invalid_puzzle_size_is_serde() {
            // Puzzle's Deserialize rejects n outside 1..=9, so this fails at parse
            // time (a genuine Serde error) rather than during propagation.
            let json = r#"{"version":1,"puzzle":{"n":0,"cages":[]}}"#;
            let mut state = AppState::default();
            assert!(matches!(
                apply_loaded(&mut state, json),
                Err(Error::Serde(_))
            ));
        }

        #[test]
        fn apply_loaded_missing_version_field_is_serde() {
            // `version` is a required envelope field with no serde default.
            let json = r#"{"puzzle":{"n":3,"cages":[]}}"#;
            let mut state = AppState::default();
            assert!(matches!(
                apply_loaded(&mut state, json),
                Err(Error::Serde(_))
            ));
        }
    }

    // ---- Category 2: state invariants after each command ----

    mod invariants {
        use super::helpers::{all_cells, cells, unique_3x3_app_state, with_solution_3x3};
        use crate::{
            AppState, fix, insert_cage, new_empty, new_latin_square, remove_cage_at, unfix,
        };
        use mathdoku::{Cell, Grid, Values};
        use rand::{SeedableRng, rngs::StdRng};

        #[test]
        fn new_empty_sets_puzzle_and_dirty() {
            let mut state = AppState::default();
            let result = new_empty(&mut state, 4).unwrap();
            assert_eq!(result.puzzle.n(), 4);
            // Without-Solution mode: no solution snapshot.
            assert!(result.solution.is_none());
            assert!(state.puzzle.is_some());
            assert!(state.solution.is_none());
            assert!(state.dirty);
            assert!(state.path.is_none());
        }

        #[test]
        fn new_empty_clears_existing_path() {
            let mut state = AppState {
                path: Some("/old/path.mathdoku".to_string()),
                ..AppState::default()
            };
            let _ = new_empty(&mut state, 4).unwrap();
            assert!(state.path.is_none());
        }

        #[test]
        fn new_empty_establishes_invariants() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            assert!(state.puzzle.is_some());
            assert!(state.solution.is_none());
            assert!(state.current.is_some());
            // current is unconstrained: every cell holds the full value set.
            let current = state.current.as_ref().unwrap();
            for cell in all_cells(4) {
                assert_eq!(current.cell_values(cell).unwrap(), Values::all(4));
            }
            assert!(state.path.is_none());
            assert!(state.dirty);
            assert!(state.active.is_none());
        }

        #[test]
        fn new_latin_square_establishes_invariants() {
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(99);
            let _ = new_latin_square(&mut state, 4, &mut rng).unwrap();
            assert!(state.puzzle.is_some());
            assert!(state.solution.is_some());
            // current == solution initially.
            assert_eq!(state.current, state.solution);
            assert!(state.path.is_none());
            assert!(state.dirty);
        }

        #[test]
        fn insert_cage_uses_author_target_without_solution() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let cells = [Cell::new(0, 0), Cell::new(0, 1)];
            let st = insert_cage(&mut state, &cells, mathdoku::Operator::Add, Some(7)).unwrap();
            let cage = st.puzzle.cages().next().unwrap();
            assert_eq!(cage.operation().target, 7);
            assert!(st.solution.is_none());
        }

        #[test]
        fn insert_cage_with_solution_keeps_current_constrained() {
            let mut state = with_solution_3x3();
            let region = cells(&[(0, 0)]);
            let st = insert_cage(&mut state, &region, mathdoku::Operator::Given, None).unwrap();
            let puzzle = state.puzzle.as_ref().unwrap();
            assert!(puzzle.cages().any(|c| c.cells() == region));
            let expected = state.solution.as_ref().unwrap().constrain(puzzle).unwrap();
            assert_eq!(state.current.as_ref().unwrap(), &expected);
            assert!(state.dirty);
            assert!(st.solution.is_some());
        }

        #[test]
        fn insert_cage_without_solution_keeps_current_constrained() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let region = cells(&[(0, 0), (0, 1)]);
            let _ = insert_cage(&mut state, &region, mathdoku::Operator::Add, Some(3)).unwrap();
            let puzzle = state.puzzle.as_ref().unwrap();
            assert!(puzzle.cages().any(|c| c.cells() == region));
            let expected = Grid::new(4).unwrap().constrain(puzzle).unwrap();
            assert_eq!(state.current.as_ref().unwrap(), &expected);
            assert!(state.dirty);
        }

        #[test]
        fn remove_cage_re_constrains_current() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let region = cells(&[(0, 0), (0, 1)]);
            let _ = insert_cage(&mut state, &region, mathdoku::Operator::Add, Some(3)).unwrap();
            let _ = insert_cage(
                &mut state,
                &cells(&[(1, 0)]),
                mathdoku::Operator::Given,
                Some(2),
            )
            .unwrap();
            let poly = mathdoku::Polyomino::from_cells(&region).unwrap();
            let _ = remove_cage_at(&mut state, &poly).unwrap();
            let puzzle = state.puzzle.as_ref().unwrap();
            assert!(!puzzle.cages().any(|c| c.cells() == region));
            assert!(puzzle.cages().any(|c| c.cells() == cells(&[(1, 0)])));
            let expected = Grid::new(4).unwrap().constrain(puzzle).unwrap();
            assert_eq!(state.current.as_ref().unwrap(), &expected);
            assert!(state.dirty);
        }

        #[test]
        fn fix_sets_solution_leaves_puzzle_and_current() {
            let mut state = unique_3x3_app_state();
            let puzzle_before = state.puzzle.clone();
            let current_before = state.current.clone();
            let _ = fix(&mut state).unwrap();
            assert!(state.solution.is_some());
            assert_eq!(state.puzzle, puzzle_before);
            assert_eq!(state.current, current_before);
            assert!(state.dirty);
            let sol = state.solution.as_ref().unwrap();
            assert_eq!(
                sol.cell_values(Cell::new(0, 0)).unwrap(),
                Values::new(&[1]).unwrap()
            );
        }

        #[test]
        fn unfix_clears_solution() {
            let mut state = AppState::default();
            let _ = new_latin_square(&mut state, 3, &mut rand::rng()).unwrap();
            let st = unfix(&mut state).unwrap();
            assert!(st.solution.is_none());
            assert!(state.solution.is_none());
        }

        #[test]
        fn unfix_clears_solution_leaves_puzzle_and_current() {
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(5);
            let _ = new_latin_square(&mut state, 4, &mut rng).unwrap();
            let puzzle_before = state.puzzle.clone();
            let current_before = state.current.clone();
            let _ = unfix(&mut state).unwrap();
            assert!(state.solution.is_none());
            assert_eq!(state.puzzle, puzzle_before);
            assert_eq!(state.current, current_before);
            assert!(state.dirty);
        }

        #[test]
        fn apply_loaded_clears_dirty_and_active_but_leaves_path() {
            use crate::{apply_loaded, serialize_save};
            use mathdoku::Puzzle;
            let source = AppState {
                puzzle: Some(Puzzle::new(5).unwrap()),
                current: Some(Grid::new(5).unwrap()),
                ..AppState::default()
            };
            let json = serialize_save(&source).unwrap();
            let mut state = AppState {
                path: Some("/x.mathdoku".to_string()),
                dirty: true,
                active: Some(Cell::new(2, 3)),
                ..AppState::default()
            };
            let _ = apply_loaded(&mut state, &json).unwrap();
            assert!(!state.dirty);
            assert!(state.active.is_none());
            // The core deliberately leaves `path` untouched — its doc states "the
            // caller is responsible for recording the file path". #55's
            // "path == None (the wrapper sets it)" is the wrapper-level
            // post-condition, not the core's.
            assert_eq!(state.path.as_deref(), Some("/x.mathdoku"));
        }
    }

    // ---- Category 3: mode-transition chains ----

    mod mode_transitions {
        use super::helpers::{all_cells, cells, unique_3x3_app_state};
        use crate::{AppState, Error, fix, insert_cage, new_empty, new_latin_square, unfix};
        use mathdoku::{Cell, Operator};
        use rand::{SeedableRng, rngs::StdRng};

        #[test]
        fn chain_new_empty_given_add_fix_unfix_multiply() {
            // A 2×2 Latin square is uniquely determined by its top-left cell, so
            // `fix` succeeds after only two cages.
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 2).unwrap();
            let _ = insert_cage(&mut state, &cells(&[(0, 0)]), Operator::Given, Some(1)).unwrap();
            let _ = insert_cage(
                &mut state,
                &cells(&[(0, 1), (1, 1)]),
                Operator::Add,
                Some(3),
            )
            .unwrap();
            let _ = fix(&mut state).unwrap();
            assert!(state.solution.is_some());
            let _ = unfix(&mut state).unwrap();
            assert!(state.solution.is_none());
            let _ = insert_cage(&mut state, &cells(&[(1, 0)]), Operator::Given, Some(2)).unwrap();
            let puzzle = state.puzzle.as_ref().unwrap();
            assert_eq!(puzzle.cages().count(), 3);
            assert!(state.solution.is_none());
        }

        #[test]
        fn new_latin_square_unfix_fix_recovers_solution() {
            // #55's literal chain (new_latin_square -> unfix -> fix with no cages)
            // only recovers a unique solution for n=1, which has a single
            // completion — but generate_latin_square(1) hangs (#67), and any n>=2
            // cageless puzzle has many completions. So we pin the generated
            // solution with Given cages first, then confirm the unfix -> fix
            // round-trip recovers the identical grid.
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(2024);
            let _ = new_latin_square(&mut state, 3, &mut rng).unwrap();
            let original = state.solution.clone().unwrap();
            for cell in all_cells(3) {
                let v = u64::from(original.cell_values(cell).unwrap().values()[0]);
                let _ = insert_cage(&mut state, &[cell], Operator::Given, Some(v)).unwrap();
            }
            let _ = unfix(&mut state).unwrap();
            assert!(state.solution.is_none());
            let _ = fix(&mut state).unwrap();
            assert_eq!(state.solution.as_ref(), Some(&original));
        }

        #[test]
        fn new_latin_square_unfix_fix_without_cages_is_not_unique() {
            // The literal #55 chain: a cageless 2×2 has multiple completions, so
            // the unfix -> fix round-trip cannot recover a unique solution. (n=1,
            // the only cageless-unique size, hangs in generate_latin_square — #67.)
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(11);
            let _ = new_latin_square(&mut state, 2, &mut rng).unwrap();
            let _ = unfix(&mut state).unwrap();
            assert!(matches!(fix(&mut state), Err(Error::NotUnique)));
        }

        #[test]
        fn new_latin_square_insert_unfix_insert_fix() {
            // Confirms target re-derivation across a mode flip: a With-Solution
            // insert derives its target from the solution; after unfix, a second
            // insert takes an author target; fix then recovers the original grid.
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(7);
            let _ = new_latin_square(&mut state, 2, &mut rng).unwrap();
            let solution = state.solution.clone().unwrap();
            let value_at = |r: usize, c: usize| {
                u64::from(solution.cell_values(Cell::new(r, c)).unwrap().values()[0])
            };

            // With-Solution: target derived from the solution.
            let st1 = insert_cage(&mut state, &cells(&[(0, 0)]), Operator::Given, None).unwrap();
            let derived = st1
                .puzzle
                .cages()
                .find(|c| c.cells() == cells(&[(0, 0)]))
                .unwrap()
                .operation()
                .target;
            assert_eq!(derived, value_at(0, 0));

            let _ = unfix(&mut state).unwrap();
            assert!(state.solution.is_none());

            // Without-Solution: author supplies the target for a different cell.
            let _ = insert_cage(
                &mut state,
                &cells(&[(0, 1)]),
                Operator::Given,
                Some(value_at(0, 1)),
            )
            .unwrap();

            let _ = fix(&mut state).unwrap();
            assert_eq!(state.solution.as_ref(), Some(&solution));
        }

        #[test]
        fn fix_twice_is_idempotent_on_solution() {
            let mut state = unique_3x3_app_state();
            let _ = fix(&mut state).unwrap();
            let solution_after_first = state.solution.clone();
            let _ = fix(&mut state).unwrap();
            assert_eq!(state.solution, solution_after_first);
            assert!(state.solution.is_some());
        }
    }

    // ---- Category 4: operator target derivation (With-Solution) ----

    mod target_derivation {
        use super::helpers::{cells, with_solution_3x3};
        use crate::insert_cage;
        use mathdoku::Operator;

        // Inserts a With-Solution cage (target derived from the solution) and
        // returns the derived target. The solution is `known_3x3_solution`:
        //   1 2 3 / 2 3 1 / 3 1 2
        fn derived_target(op: Operator, region: &[(usize, usize)]) -> u64 {
            let mut state = with_solution_3x3();
            let region_cells = cells(region);
            let st = insert_cage(&mut state, &region_cells, op, None).unwrap();
            st.puzzle
                .cages()
                .find(|c| c.cells() == region_cells)
                .unwrap()
                .operation()
                .target
        }

        #[test]
        fn given_derives_cell_value() {
            // (0,0) = 1.
            assert_eq!(derived_target(Operator::Given, &[(0, 0)]), 1);
        }

        #[test]
        fn add_derives_sum() {
            // (0,0)=1 + (0,1)=2 = 3.
            assert_eq!(derived_target(Operator::Add, &[(0, 0), (0, 1)]), 3);
        }

        #[test]
        fn multiply_derives_product() {
            // (0,0)=1 * (0,1)=2 = 2.
            assert_eq!(derived_target(Operator::Multiply, &[(0, 0), (0, 1)]), 2);
        }

        #[test]
        fn subtract_derives_absolute_difference() {
            // |1 - 2| = 1.
            assert_eq!(derived_target(Operator::Subtract, &[(0, 0), (0, 1)]), 1);
        }

        #[test]
        fn divide_derives_quotient() {
            // max(1,2) / min(1,2) = 2.
            assert_eq!(derived_target(Operator::Divide, &[(0, 0), (0, 1)]), 2);
        }
    }

    // ---- Category 5: save-format wire stability ----

    mod save_format {
        use super::helpers::{cells, save_round_trip};
        use crate::{
            AppState, SAVE_VERSION, apply_loaded, insert_cage, new_empty, new_latin_square,
            serialize_save,
        };
        use mathdoku::{Cell, Grid, Operator, Puzzle};
        use rand::{SeedableRng, rngs::StdRng};

        #[test]
        fn save_version_is_one() {
            assert_eq!(SAVE_VERSION, 1);
        }

        #[test]
        fn serialize_save_apply_loaded_round_trips() {
            let state = AppState {
                puzzle: Some(Puzzle::new(5).unwrap()),
                current: Some(Grid::new(5).unwrap()),
                ..AppState::default()
            };
            let json = serialize_save(&state).unwrap();

            let mut loaded = AppState::default();
            let designer = apply_loaded(&mut loaded, &json).unwrap();
            assert_eq!(designer.puzzle.n(), 5);
            assert!(!loaded.dirty);
            assert!(loaded.active.is_none());
            assert_eq!(loaded.puzzle.unwrap().n(), 5);
        }

        #[test]
        fn without_solution_save_omits_solution_key() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let _ = insert_cage(
                &mut state,
                &cells(&[(0, 0), (0, 1)]),
                Operator::Add,
                Some(3),
            )
            .unwrap();
            let json = serialize_save(&state).unwrap();
            assert!(!json.contains("\"solution\""));
        }

        #[test]
        fn with_solution_save_contains_solution_key() {
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(1);
            let _ = new_latin_square(&mut state, 4, &mut rng).unwrap();
            let json = serialize_save(&state).unwrap();
            assert!(json.contains("\"solution\""));
        }

        #[test]
        fn without_solution_round_trips_bit_identical() {
            let mut source = AppState::default();
            let _ = new_empty(&mut source, 4).unwrap();
            let _ = insert_cage(
                &mut source,
                &cells(&[(0, 0), (0, 1)]),
                Operator::Add,
                Some(3),
            )
            .unwrap();
            let loaded = save_round_trip(&source);
            assert_eq!(loaded.puzzle, source.puzzle);
            assert_eq!(loaded.solution, source.solution);
            assert_eq!(loaded.current, source.current);
            assert_eq!(
                serialize_save(&loaded).unwrap(),
                serialize_save(&source).unwrap()
            );
        }

        #[test]
        fn with_solution_round_trips_bit_identical() {
            let mut source = AppState::default();
            let mut rng = StdRng::seed_from_u64(8);
            let _ = new_latin_square(&mut source, 4, &mut rng).unwrap();
            let loaded = save_round_trip(&source);
            assert_eq!(loaded.puzzle, source.puzzle);
            assert_eq!(loaded.solution, source.solution);
            assert_eq!(loaded.current, source.current);
            assert_eq!(
                serialize_save(&loaded).unwrap(),
                serialize_save(&source).unwrap()
            );
        }

        #[test]
        fn minimal_hand_written_envelope_loads() {
            // Pins the on-disk wire format against accidental drift.
            let json = r#"{
  "version": 1,
  "puzzle": {
    "n": 2,
    "cages": [
      {
        "polyomino": [{"row": 0, "column": 0}],
        "operation": {"operator": "Given", "target": 1}
      }
    ]
  }
}"#;
            let mut state = AppState::default();
            let designer = apply_loaded(&mut state, json).unwrap();
            assert_eq!(designer.puzzle.n(), 2);
            assert!(designer.solution.is_none());
            assert_eq!(designer.puzzle.cages().count(), 1);
            assert_eq!(
                designer
                    .current
                    .cell_values(Cell::new(0, 0))
                    .unwrap()
                    .values(),
                vec![1]
            );
        }
    }

    // ---- Category 6: deterministic generation ----

    mod generation {
        use crate::{AppState, new_latin_square};
        use mathdoku::{Cell, Grid};
        use rand::{SeedableRng, rngs::StdRng};

        fn solution_for(n: usize, seed: u64) -> Grid {
            let mut state = AppState::default();
            let mut rng = StdRng::seed_from_u64(seed);
            let _ = new_latin_square(&mut state, n, &mut rng).unwrap();
            state.solution.unwrap()
        }

        fn is_valid_latin_square(grid: &Grid, n: usize) -> bool {
            let expected: Vec<u8> = (1..=n as u8).collect();
            let line_ok = |cells: Vec<u8>| {
                let mut sorted = cells;
                sorted.sort_unstable();
                sorted == expected
            };
            (0..n).all(|r| {
                line_ok(
                    (0..n)
                        .map(|c| grid.cell_values(Cell::new(r, c)).unwrap().values()[0])
                        .collect(),
                )
            }) && (0..n).all(|c| {
                line_ok(
                    (0..n)
                        .map(|r| grid.cell_values(Cell::new(r, c)).unwrap().values()[0])
                        .collect(),
                )
            })
        }

        #[test]
        fn same_seed_same_solution() {
            assert_eq!(solution_for(4, 42), solution_for(4, 42));
        }

        #[test]
        fn different_seeds_differ() {
            // Sanity check (not exhaustive): a spread of fixed seeds should not
            // all collapse onto a single 4×4 square.
            let grids: std::collections::HashSet<Grid> =
                (1u64..=8).map(|seed| solution_for(4, seed)).collect();
            assert!(grids.len() > 1, "every seed produced the same grid");
        }

        #[test]
        fn generated_is_valid_latin_square_for_n_2_through_9() {
            // n=1 is excluded: generate_latin_square(1) infinite-loops — see #67.
            for n in 2..=9 {
                let grid = solution_for(n, 100 + n as u64);
                assert!(
                    is_valid_latin_square(&grid, n),
                    "n={n} is not a valid Latin square"
                );
            }
        }

        #[test]
        fn generated_is_valid_latin_square_for_n_1() {
            let grid = solution_for(1, 1);
            assert!(is_valid_latin_square(&grid, 1));
        }
    }

    // ---- Category 8: pre-condition and trivial-getter tests ----

    mod getters {
        use super::helpers::cells;
        use crate::{
            AppState, apply_loaded, get_doc_state, get_puzzle, insert_cage, new_empty,
            serialize_save, set_active_cell,
        };
        use mathdoku::{Cell, Grid, Operator, Puzzle};

        #[test]
        fn get_doc_state_returns_current_values() {
            let state = AppState {
                dirty: true,
                path: Some("/some/path.mathdoku".to_string()),
                ..AppState::default()
            };
            let doc = get_doc_state(&state);
            assert!(doc.dirty);
            assert_eq!(doc.path.as_deref(), Some("/some/path.mathdoku"));
        }

        #[test]
        fn get_doc_state_default_is_clean_with_no_path() {
            let state = AppState::default();
            let doc = get_doc_state(&state);
            assert!(!doc.dirty);
            assert!(doc.path.is_none());
        }

        #[test]
        fn get_puzzle_returns_none_when_no_puzzle() {
            let state = AppState::default();
            assert!(get_puzzle(&state).is_none());
        }

        #[test]
        fn get_puzzle_returns_puzzle_when_loaded() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 6).unwrap();
            let p = get_puzzle(&state).unwrap();
            assert_eq!(p.puzzle.n(), 6);
        }

        #[test]
        fn get_puzzle_some_after_apply_loaded() {
            let source = AppState {
                puzzle: Some(Puzzle::new(3).unwrap()),
                current: Some(Grid::new(3).unwrap()),
                ..AppState::default()
            };
            let json = serialize_save(&source).unwrap();
            let mut state = AppState::default();
            let _ = apply_loaded(&mut state, &json).unwrap();
            assert!(get_puzzle(&state).is_some());
        }

        #[test]
        fn set_active_cell_updates_state_and_designer_state() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            set_active_cell(&mut state, Cell::new(2, 3));
            assert_eq!(state.active, Some(Cell::new(2, 3)));
            let designer = state.to_designer_state().unwrap();
            assert_eq!(designer.active, Cell::new(2, 3));
        }

        #[test]
        fn to_designer_state_none_until_puzzle_and_current() {
            let only_puzzle = AppState {
                puzzle: Some(Puzzle::new(4).unwrap()),
                ..AppState::default()
            };
            assert!(only_puzzle.to_designer_state().is_none());

            let only_current = AppState {
                current: Some(Grid::new(4).unwrap()),
                ..AppState::default()
            };
            assert!(only_current.to_designer_state().is_none());

            let both = AppState {
                puzzle: Some(Puzzle::new(4).unwrap()),
                current: Some(Grid::new(4).unwrap()),
                ..AppState::default()
            };
            assert!(both.to_designer_state().is_some());
        }

        #[test]
        fn to_designer_state_always_has_empty_provisional_cages() {
            let mut state = AppState::default();
            let _ = new_empty(&mut state, 4).unwrap();
            let _ = insert_cage(
                &mut state,
                &cells(&[(0, 0), (0, 1)]),
                Operator::Add,
                Some(3),
            )
            .unwrap();
            let designer = state.to_designer_state().unwrap();
            assert!(designer.provisional_cages.is_empty());
        }
    }

    // ---- Category 9: cage-shape edge cases ----

    mod cage_shapes {
        use super::helpers::{cells, without_solution};
        use crate::{Error, insert_cage};
        use mathdoku::{Cell, Operator};

        #[test]
        fn single_cell_given_succeeds() {
            let mut state = without_solution(4);
            let region = cells(&[(0, 0)]);
            let st = insert_cage(&mut state, &region, Operator::Given, Some(3)).unwrap();
            assert!(st.puzzle.cages().any(|c| c.cells() == region));
            assert!(!st.current.cell_values(Cell::new(0, 0)).unwrap().is_empty());
        }

        #[test]
        fn row_pair_all_binary_operators_succeed() {
            for (op, target) in [
                (Operator::Add, 3),
                (Operator::Subtract, 1),
                (Operator::Multiply, 2),
                (Operator::Divide, 2),
            ] {
                let mut state = without_solution(4);
                let st =
                    insert_cage(&mut state, &cells(&[(0, 0), (0, 1)]), op, Some(target)).unwrap();
                assert_eq!(st.puzzle.cages().count(), 1);
                assert!(!st.current.cell_values(Cell::new(0, 0)).unwrap().is_empty());
            }
        }

        #[test]
        fn column_pair_all_binary_operators_succeed() {
            for (op, target) in [
                (Operator::Add, 3),
                (Operator::Subtract, 1),
                (Operator::Multiply, 2),
                (Operator::Divide, 2),
            ] {
                let mut state = without_solution(4);
                let st =
                    insert_cage(&mut state, &cells(&[(0, 0), (1, 0)]), op, Some(target)).unwrap();
                assert_eq!(st.puzzle.cages().count(), 1);
                assert!(!st.current.cell_values(Cell::new(0, 0)).unwrap().is_empty());
            }
        }

        #[test]
        fn row_triomino_add_and_multiply_succeed() {
            for (op, target) in [(Operator::Add, 6), (Operator::Multiply, 6)] {
                let mut state = without_solution(4);
                let region = cells(&[(0, 0), (0, 1), (0, 2)]);
                let st = insert_cage(&mut state, &region, op, Some(target)).unwrap();
                assert!(!st.current.cell_values(Cell::new(0, 0)).unwrap().is_empty());
            }
        }

        #[test]
        fn l_shape_add_succeeds() {
            let mut state = without_solution(4);
            let region = cells(&[(0, 0), (1, 0), (1, 1)]);
            let st = insert_cage(&mut state, &region, Operator::Add, Some(6)).unwrap();
            assert!(!st.current.cell_values(Cell::new(0, 0)).unwrap().is_empty());
        }

        #[test]
        fn t_shape_multiply_succeeds() {
            // T-tetromino: (0,0),(0,1),(0,2),(1,1).
            let mut state = without_solution(4);
            let region = cells(&[(0, 0), (0, 1), (0, 2), (1, 1)]);
            let st = insert_cage(&mut state, &region, Operator::Multiply, Some(24)).unwrap();
            assert!(st.puzzle.cages().any(|c| c.cells() == region));
            assert!(!st.current.cell_values(Cell::new(0, 0)).unwrap().is_empty());
        }

        #[test]
        fn square_tetromino_add_succeeds() {
            // 2×2 square block.
            let mut state = without_solution(4);
            let region = cells(&[(0, 0), (0, 1), (1, 0), (1, 1)]);
            let st = insert_cage(&mut state, &region, Operator::Add, Some(10)).unwrap();
            assert!(st.puzzle.cages().any(|c| c.cells() == region));
            assert!(!st.current.cell_values(Cell::new(0, 0)).unwrap().is_empty());
        }

        #[test]
        fn boundary_cages_succeed() {
            // Corner and edge cages on a 3×3 — confirm no special-case bugs.
            let mut state = without_solution(3);
            let _ = insert_cage(&mut state, &cells(&[(2, 2)]), Operator::Given, Some(1)).unwrap();
            let _ = insert_cage(
                &mut state,
                &cells(&[(0, 2), (1, 2)]),
                Operator::Add,
                Some(5),
            )
            .unwrap();
            let st = insert_cage(
                &mut state,
                &cells(&[(2, 0), (2, 1)]),
                Operator::Subtract,
                Some(1),
            )
            .unwrap();
            assert_eq!(st.puzzle.cages().count(), 3);
        }

        #[test]
        fn triomino_given_returns_err() {
            let mut state = without_solution(4);
            let region = cells(&[(0, 0), (0, 1), (0, 2)]);
            assert!(matches!(
                insert_cage(&mut state, &region, Operator::Given, Some(1)),
                Err(Error::Mathdoku(mathdoku::Error::InfeasibleOperation(_, _)))
            ));
        }

        #[test]
        fn triomino_subtract_returns_err() {
            let mut state = without_solution(4);
            let region = cells(&[(0, 0), (0, 1), (0, 2)]);
            assert!(matches!(
                insert_cage(&mut state, &region, Operator::Subtract, Some(1)),
                Err(Error::Mathdoku(mathdoku::Error::InfeasibleOperation(_, _)))
            ));
        }
    }

    // ---- Category 7: property tests ----

    mod properties {
        use crate::{
            AppState, apply_loaded, insert_cage, new_empty, new_latin_square, remove_cage_at,
            serialize_save, unfix,
        };
        use mathdoku::{Cell, Grid, Operator};
        use proptest::prelude::*;
        use rand::{SeedableRng, rngs::StdRng};

        #[derive(Debug, Clone)]
        enum Op {
            Given {
                r: usize,
                c: usize,
                target: u64,
            },
            AddPair {
                r: usize,
                c: usize,
                horizontal: bool,
                target: u64,
            },
            Remove {
                r: usize,
                c: usize,
            },
        }

        fn op_strategy(n: usize) -> impl Strategy<Value = Op> {
            prop_oneof![
                (0..n, 0..n, 1u64..=n as u64).prop_map(|(r, c, target)| Op::Given { r, c, target }),
                (0..n, 0..n, any::<bool>(), 2u64..=2 * n as u64).prop_map(
                    |(r, c, horizontal, target)| Op::AddPair {
                        r,
                        c,
                        horizontal,
                        target
                    }
                ),
                (0..n, 0..n).prop_map(|(r, c)| Op::Remove { r, c }),
            ]
        }

        // Generates a grid size and a short operation sequence for that size.
        fn problem() -> impl Strategy<Value = (usize, Vec<Op>)> {
            (2usize..=4).prop_flat_map(|n| (Just(n), prop::collection::vec(op_strategy(n), 0..=10)))
        }

        // Applies one operation, returning whether it succeeded.
        fn apply(state: &mut AppState, op: &Op) -> bool {
            match *op {
                Op::Given { r, c, target } => {
                    insert_cage(state, &[Cell::new(r, c)], Operator::Given, Some(target)).is_ok()
                }
                Op::AddPair {
                    r,
                    c,
                    horizontal,
                    target,
                } => {
                    let second = if horizontal {
                        Cell::new(r, c + 1)
                    } else {
                        Cell::new(r + 1, c)
                    };
                    insert_cage(
                        state,
                        &[Cell::new(r, c), second],
                        Operator::Add,
                        Some(target),
                    )
                    .is_ok()
                }
                Op::Remove { r, c } => {
                    let Ok(poly) = mathdoku::Polyomino::from_cells(&[Cell::new(r, c)]) else {
                        return false;
                    };
                    remove_cage_at(state, &poly).is_ok()
                }
            }
        }

        // The core state invariant: `current` always equals the puzzle re-applied
        // to either the fixed solution (With-Solution) or a fresh grid (Without).
        fn assert_consistent(state: &AppState) {
            let puzzle = state.puzzle.as_ref().unwrap();
            let current = state.current.as_ref().unwrap();
            let expected = state.solution.as_ref().map_or_else(
                || Grid::new(puzzle.n()).unwrap().constrain(puzzle).unwrap(),
                |sol| sol.constrain(puzzle).unwrap(),
            );
            assert_eq!(current, &expected);
        }

        // `fix`/`unfix` are deliberately excluded from the consistency generator:
        // they flip mode without recomputing `current`, so the stated invariant
        // does not hold across them. They are exercised by the dirty-flag property
        // below (which only inspects `dirty`).

        fn bootstrap(n: usize, seed: u64, latin: bool) -> AppState {
            let mut state = AppState::default();
            if latin {
                let mut rng = StdRng::seed_from_u64(seed);
                let _ = new_latin_square(&mut state, n, &mut rng).unwrap();
            } else {
                let _ = new_empty(&mut state, n).unwrap();
            }
            state
        }

        proptest! {
            #![proptest_config(ProptestConfig {
                cases: 64,
                failure_persistence: None,
                ..ProptestConfig::default()
            })]

            #[test]
            fn prop_state_consistency(
                (n, ops) in problem(),
                seed in any::<u64>(),
                latin in any::<bool>(),
            ) {
                // Generated ops always pass an explicit author target, so the
                // With-Solution target-derivation path (target = None) is covered
                // by Category 4, not here; this property only exercises the
                // current/puzzle consistency invariant.
                let mut state = bootstrap(n, seed, latin);
                assert_consistent(&state);
                for op in &ops {
                    if apply(&mut state, op) {
                        assert_consistent(&state);
                    }
                }
            }

            #[test]
            fn prop_round_trip_stability(
                (n, ops) in problem(),
                seed in any::<u64>(),
                latin in any::<bool>(),
            ) {
                let mut state = bootstrap(n, seed, latin);
                for op in &ops {
                    let _ = apply(&mut state, op);
                }
                let json = serialize_save(&state).unwrap();
                let mut loaded = AppState::default();
                let _ = apply_loaded(&mut loaded, &json).unwrap();
                prop_assert_eq!(&loaded.puzzle, &state.puzzle);
                prop_assert_eq!(&loaded.solution, &state.solution);
                prop_assert_eq!(&loaded.current, &state.current);
            }

            #[test]
            fn prop_dirty_monotonicity(
                (n, ops) in problem(),
                seed in any::<u64>(),
                latin in any::<bool>(),
                do_unfix in any::<bool>(),
            ) {
                let mut state = bootstrap(n, seed, latin);
                prop_assert!(state.dirty);
                for op in &ops {
                    if apply(&mut state, op) {
                        prop_assert!(state.dirty);
                    }
                }
                if do_unfix {
                    // unfix always succeeds with a puzzle loaded and sets dirty.
                    let _ = unfix(&mut state).unwrap();
                    prop_assert!(state.dirty);
                }
                // apply_loaded is the only command that clears dirty.
                let json = serialize_save(&state).unwrap();
                let mut loaded = AppState::default();
                let _ = apply_loaded(&mut loaded, &json).unwrap();
                prop_assert!(!loaded.dirty);
            }
        }
    }
}
