//! [`SelectionOverlay`] component: active cell highlight and provisional cage overlay.

#![allow(
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::single_char_lifetime_names // generated by view! macro
)]

use std::collections::HashSet;

use leptos::prelude::*;
use mathdoku::Cell;

use super::puzzle::InteractionState;
use crate::geometry::origin;

use crate::theme::{ACCENT, PROVISIONAL_FILL, PROVISIONAL_STROKE};
const SELECTION: f64 = 3.5;

/// Provisional cage fill rectangles only — rendered below gridlines so the
/// thin cell boundaries remain equally visible inside and outside the cage.
#[component]
pub fn ProvisionalFills() -> impl IntoView {
    #[allow(clippy::panic)]
    let ctx = use_context::<InteractionState>()
        .unwrap_or_else(|| panic!("ProvisionalFills must be inside Puzzle"));
    let InteractionState {
        designer_state,
        cell_size: cell,
        ..
    } = ctx;

    move || {
        use leptos::prelude::IntoAny;
        let st = designer_state.get();
        st.provisional_cages
            .iter()
            .flat_map(|cage| {
                cage.cells().into_iter().map(move |c| {
                    let (x, y) = origin(cell, c.row(), c.column());
                    view! { <rect x=x y=y width=cell height=cell fill=PROVISIONAL_FILL /> }
                        .into_any()
                })
            })
            .collect::<Vec<_>>()
    }
}

/// Provisional cage border strokes and active cell highlight — rendered above gridlines.
#[component]
pub fn SelectionOverlay() -> impl IntoView {
    #[allow(clippy::panic)]
    let ctx = use_context::<InteractionState>()
        .unwrap_or_else(|| panic!("SelectionOverlay must be inside Puzzle"));
    let InteractionState {
        designer_state,
        cell_size: cell,
        ..
    } = ctx;

    move || {
        use leptos::prelude::IntoAny;
        let line_w = SELECTION;
        let inset = line_w / 2.0;
        let st = designer_state.get();

        let mut elements: Vec<_> = Vec::new();

        // Provisional cage border strokes.
        for cage in &st.provisional_cages {
            let cell_set: HashSet<Cell> = cage.cells().into_iter().collect();
            for c in cage.cells() {
                let (x, y) = origin(cell, c.row(), c.column());
                let stroke = PROVISIONAL_STROKE;
                if c.row() == 0 || !cell_set.contains(&Cell::new(c.row() - 1, c.column())) {
                    let (x1, x2, yy) = (x + inset, x + cell - inset, y + inset);
                    elements.push(view! { <line x1=x1 y1=yy x2=x2 y2=yy stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
                if !cell_set.contains(&Cell::new(c.row() + 1, c.column())) {
                    let (x1, x2, yy) = (x + inset, x + cell - inset, y + cell - inset);
                    elements.push(view! { <line x1=x1 y1=yy x2=x2 y2=yy stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
                if c.column() == 0 || !cell_set.contains(&Cell::new(c.row(), c.column() - 1)) {
                    let (xx, y1, y2) = (x + inset, y + inset, y + cell - inset);
                    elements.push(view! { <line x1=xx y1=y1 x2=xx y2=y2 stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
                if !cell_set.contains(&Cell::new(c.row(), c.column() + 1)) {
                    let (xx, y1, y2) = (x + cell - inset, y + inset, y + cell - inset);
                    elements.push(view! { <line x1=xx y1=y1 x2=xx y2=y2 stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
            }
        }

        // Active cell selection rect.
        let (x, y) = origin(cell, st.active.row(), st.active.column());
        elements.push(
            view! {
                <rect
                    x={x + inset} y={y + inset}
                    width={cell - line_w} height={cell - line_w}
                    fill="none"
                    stroke=ACCENT
                    stroke-width=line_w
                />
            }
            .into_any(),
        );

        elements
    }
}
