//! [`SelectionOverlay`] component: mode-dependent cell/slot highlight.

#![allow(
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::single_char_lifetime_names // generated by view! macro
)]

use std::collections::HashSet;

use leptos::prelude::*;
use mathdoku_designer_shared::Mode;

use super::puzzle::{GridContext, MARGIN};

use crate::theme::{ACCENT, PROVISIONAL_FILL, PROVISIONAL_STROKE};
const SELECTION: f64 = 3.5;

const fn origin(cell: f64, row: usize, col: usize) -> (f64, f64) {
    (
        (col as f64).mul_add(cell, MARGIN),
        (row as f64).mul_add(cell, MARGIN),
    )
}

/// Reactive highlight overlay. Reads grid context for mode and selection state.
#[component]
pub fn SelectionOverlay() -> impl IntoView {
    #[allow(clippy::panic)]
    let ctx = use_context::<GridContext>()
        .unwrap_or_else(|| panic!("SelectionOverlay must be inside Puzzle"));
    let GridContext {
        mode,
        selected_cell,
        selected_slot,
        slot_cells,
        provisional_region,
        cell,
        ..
    } = ctx;

    move || {
        use leptos::prelude::IntoAny;
        let line_w = SELECTION;
        let inset = line_w / 2.0;

        let mut elements: Vec<_> = Vec::new();

        // Provisional region overlay (always drawn when non-empty).
        let region = provisional_region.get();
        if !region.is_empty() {
            let cell_set: HashSet<(usize, usize)> = region.iter().copied().collect();
            for &(r, c) in &region {
                let (x, y) = origin(cell, r, c);
                // Fill rect.
                elements.push(
                    view! {
                        <rect x=x y=y width=cell height=cell fill=PROVISIONAL_FILL />
                    }
                    .into_any(),
                );
                // Border lines on outer edges.
                let stroke = PROVISIONAL_STROKE;
                if r == 0 || !cell_set.contains(&(r - 1, c)) {
                    let (x1, x2, yy) = (x + inset, x + cell - inset, y + inset);
                    elements.push(view! { <line x1=x1 y1=yy x2=x2 y2=yy stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
                if !cell_set.contains(&(r + 1, c)) {
                    let (x1, x2, yy) = (x + inset, x + cell - inset, y + cell - inset);
                    elements.push(view! { <line x1=x1 y1=yy x2=x2 y2=yy stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
                if c == 0 || !cell_set.contains(&(r, c - 1)) {
                    let (xx, y1, y2) = (x + inset, y + inset, y + cell - inset);
                    elements.push(view! { <line x1=xx y1=y1 x2=xx y2=y2 stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
                if !cell_set.contains(&(r, c + 1)) {
                    let (xx, y1, y2) = (x + cell - inset, y + inset, y + cell - inset);
                    elements.push(view! { <line x1=xx y1=y1 x2=xx y2=y2 stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                }
            }
        }

        // Mode-dependent selection overlay.
        match mode.get() {
            Mode::Cell => {
                let (row, col) = selected_cell.get();
                let (x, y) = origin(cell, row, col);
                elements.push(
                    view! {
                        <rect
                            x={x + inset} y={y + inset}
                            width={cell - line_w} height={cell - line_w}
                            fill="none"
                            stroke=ACCENT
                            stroke-width=line_w
                        />
                    }
                    .into_any(),
                );
            }
            Mode::Slot => {
                let idx = selected_slot.get();
                let Some(cells) = slot_cells.get(idx) else {
                    return elements;
                };
                let cell_set: HashSet<(usize, usize)> = cells.iter().copied().collect();
                for &(r, c) in cells {
                    let (x, y) = origin(cell, r, c);
                    let stroke = ACCENT;
                    if r == 0 || !cell_set.contains(&(r - 1, c)) {
                        let (x1, x2, yy) = (x + inset, x + cell - inset, y + inset);
                        elements.push(view! { <line x1=x1 y1=yy x2=x2 y2=yy stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                    }
                    if !cell_set.contains(&(r + 1, c)) {
                        let (x1, x2, yy) = (x + inset, x + cell - inset, y + cell - inset);
                        elements.push(view! { <line x1=x1 y1=yy x2=x2 y2=yy stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                    }
                    if c == 0 || !cell_set.contains(&(r, c - 1)) {
                        let (xx, y1, y2) = (x + inset, y + inset, y + cell - inset);
                        elements.push(view! { <line x1=xx y1=y1 x2=xx y2=y2 stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                    }
                    if !cell_set.contains(&(r, c + 1)) {
                        let (xx, y1, y2) = (x + cell - inset, y + inset, y + cell - inset);
                        elements.push(view! { <line x1=xx y1=y1 x2=xx y2=y2 stroke=stroke stroke-width=line_w stroke-linecap="square" /> }.into_any());
                    }
                }
            }
        }

        elements
    }
}
